### ISSUE TITLE
Discrepancy in "CMS Learning Resources"

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#1198]
- http://opendata.cern.ch/collection/CMS-Learning-Resources
- http://opendata.cern.ch/search?cc=CMS-Learning-Resources

Both show different items. The former is missing http://opendata.cern.ch/record/59 while the latter is missing http://opendata.cern.ch/record/50.

**Comment by tiborsimko** [comment]
(1) Regarding the static page http://opendata.cern.ch/collection/CMS-Learning-Resources, we have static template https://github.com/cernopendata/opendata.cern.ch/blob/production/invenio_opendata/base/templates/helpers/text/cms_learning_resources.html which contains 6 records only. 

@RaoOfPhysics Perhaps you want to edit this template to add the missing bits? Do we have a screenshot?

(2) Regarding the dynamic page http://opendatadev.cern.ch/search?cc=CMS-Learning-Resources the record 50 is missing there because it is catalogued as "CMS-Open-Data-Instructions", not as "CMS-Learning-Resources". See http://opendatadev.cern.ch/search?cc=CMS-Open-Data-Instructions

@RaoOfPhysics @ArtemisLav Where do we put it? One of these? Both? What about other records in this category?

**Comment by RaoOfPhysics** [comment]
> (1) Regarding the static page http://opendata.cern.ch/collection/CMS-Learning-Resources, we have static template https://github.com/cernopendata/opendata.cern.ch/blob/production/invenio_opendata/base/templates/helpers/text/cms_learning_resources.html which contains 6 records only.
> 
> @RaoOfPhysics Perhaps you want to edit this template to add the missing bits? Do we have a screenshot?

Will do! See #1214

> (2) Regarding the dynamic page http://opendatadev.cern.ch/search?cc=CMS-Learning-Resources the record 50 is missing there because it is catalogued as "CMS-Open-Data-Instructions", not as "CMS-Learning-Resources". See http://opendatadev.cern.ch/search?cc=CMS-Open-Data-Instructions
> 
> @RaoOfPhysics @ArtemisLav Where do we put it? One of these? Both? What about other records in this category?

My feeling is that it's mis-categorised. I think record/50 should belong under CMS-Learning-Resources as it doesn't explicitly deal with the Open Data released on the portal, does it? Unless there's a derived dataset it refers to? @katilp, can you comment?

Technically, I guess many of the learning resources would qualify as "Open Data Instructions", but we need to give more meaning to the terms and classify the resources/records accordingly.

**Comment by katilp** [comment]
record/50 should be under CMS-Learning-Resources. It does refer to many derived datasets (http://opendata.cern.ch/record/203 and 204-211 for the MC). These were datasets that were released earlier than the first big release in 2014, and in that sense somewhat special. These records could be mentioned in record/50 for sake of consistency.

record/50 should not be classified "Open Data Instructions" as it is using some specially prepared derived datasets and not the standard AOD.

**Comment by RaoOfPhysics** [comment]
@katilp: This was my feeling, thank you for clarifying! :)
