### ISSUE TITLE
UI: Proposed updated navigation flow

### ISSUE THREAD

**Issue by daslerr** [cernopendata/opendata.cern.ch#1218]
I've taken into account the HST feedback (#1172) and the helpful list of challenges from Achim (#1203), as well as what we discussed in the meeting on 6 December, and I've come up with a proposal for an updated flow through the site. (See image below.) Thoughts and comments are appreciated. 

Caveat 1: This assumes the use of experiment-specific landing pages, which will aggregate content from other areas that have the relevant experiment as one of their properties (pending data model work). 

Caveat 2: This is meant to reflect conceptually the kinds of actions people might want to take on the site. It is not intended to reflect exact directory structure, and some of the labels could probably stand to be less dull. 

![opendata-navigationflow](https://cloud.githubusercontent.com/assets/3181623/21268064/605b066c-c3ad-11e6-8e25-84be94f521fb.png)

**Comment by daslerr** [comment]
Suggestions for research-related examples are in #1208. 
Flow should be updated to show paths between various possibilities and experimental landing pages.

**Comment by katilp** [comment]
@daslerr I do not see the top level division to Education and Research here, I hope we still keep it in the navigation flow. Or is it under "Possibilities"? Would the content in  #1208 go in "data recipes" there as well?

**Comment by daslerr** [comment]
That's correct. This flow removes the top-level education vs. research division. The hope is that guiding people based on what they want to do will have a largely similar effect without creating two information silos. 

Yes, I would think the content in #1208 would fit under something like data recipes or examples. We can decide on the precise words we might want to use to describe those. But the overall idea would be to have the use cases from #1208 surfaced at a higher level than they would be under the existing structure, so that they get more exposure and make it easier for users to see what Open Data is for without digging.

**Comment by katilp** [comment]
OK, thanks! But we would then have a clear top-level entry with explicit different options, instead? 
I do not see that very clearly in the graph above: I see the first-level boxes, but for example for the VMs, they are just tools to access the data so they have no value alone (only after having chosen what you want to do, i.e. what experiment data you will be looking at).

For the top-level, my impression was that HTS teachers very much liked the top-level division. They were very happy with that but suggested improvement to the page where they landed after choosing "Education". But I may be biased in this, @suenjedt and @RaoOfPhysics may have better record on that

Why I like very much the Education-Research division, is that for the education side, we should offer all resources from different experiments in the "guidance" page (as they will not care which experiment's data they do but rather what they can do with this data). For the research side it is dfferent, the division to the experiments is a must because heavier tools are involved.

**Comment by daslerr** [comment]
Here is an updated version of the navigation flow. This preserves the research vs. education distinction in some ways, because users could still choose to navigate by examples aimed at particular groups, and it brings the collections (e.g. the experiment-specific collections) to the front. I've attached a PDF mockup of what this might look like in practice. 

![opendata-navigationflow-v2](https://cloud.githubusercontent.com/assets/3181623/22826105/e67d8a9e-ef90-11e6-930c-b658b9dff8d7.png)

[OpenData-Mockups-v2.pdf](https://github.com/cernopendata/opendata.cern.ch/files/766580/OpenData-Mockups-v2.pdf)

**Comment by daslerr** [comment]
After our productive meeting on Friday, it seems the most recent navigation concept was generally accepted, and our discussion now revolves around how this will actually look in practice. So I will close this. I've started a new thread for mockups (#1228) so that portion of the conversation can continue.
