### ISSUE TITLE
ATLAS request for next sections and collections into the Education part

### ISSUE THREAD

**Issue by artfisica** [cernopendata/opendata.cern.ch#1233]
Dear experts,

**Here the PDF with the proposal and requests for ATLAS educational resources into the CERN OpenData portal.**
[ATLAS_collections_proposal_in_CERN_OpenData_website.pdf](http://opendata.atlas.cern/DataAndTools/ATLAS_collections_proposal_in_CERN_OpenData_website.pdf)

Thanks!
Susan and Arturo

**Comment by artfisica** [comment]
This is the PDF file with discussed at CERN.
@atlas-outreach-data-tools

**Comment by daslerr** [comment]
Hi Arturo. Thanks for the PDF. 

From what I can tell, several of the proposed collections would be empty. Is that right? Are you planning a major data release soon? Or is this just prepping for the future? 

Open Data isn't really set up right now for subcollections. As part of the planned overhaul, one of the ideas we're playing with is having the ability to tag the datasets so that we can display dynamic collections based on the tags, rather than the static hierarchical collections that exist now. That might be something that would work better for your purposes. With that in mind, would you be willing to wait on changes to the collections until we have that underlying structure worked out? (Currently in progress.) 

Also, from what you mentioned in passing in my office, it sounds like you guys have given some thought to how users want to find and use your data. We'd be very interested to find out more and see how this knowledge could help out with the redesign. Could I put you in touch with @sefeg (currently assigned to this issue) to talk some more about this?

**Comment by artfisica** [comment]
Dear @daslerr, @sefeg, @suenjedt, thank you very much to all of you for the reaction and feedback.
I would be happy to chat at CERN when you can/want :)
I am in a conference right now, but from next Monday, any moment will be fine for me.
About your question: yes, some collections will be empty (for the moment) but the content of those are already on production. Other content like data, well, it will arrive hopefully every year on release bases.

As you mentioned, the CERN opendata portal is changing so, to know how it will be setup is very important for us too.

Thanks again,
@artfisica

**Comment by sefeg** [comment]
Dear @artfisica,
As I am not sure that I selected the right mail address writing to you last week, I wanted to check back with you here.
I would be very happy to meet you this week, to discuss your proposal and to get feedback on our concept of the revised CERN Open Data portal.
Maybe you could [send me](https://phonebook.cern.ch/phonebook/#personDetails/?id=700401) a meeting invite (anytime this Thursday or Friday would work for me)?

**Comment by artfisica** [comment]
Dear @sefeg ,

You found the right email :)
Sorry for the delay, I just landed today on Geneva.
So, please lest meet this Thursday. Maybe 14hrs is fine for you?

I reply your email as well, so we can continue there.

Cheers and thanks,
Arturo

**Comment by artfisica** [comment]
I found you @cheatham1!

Thanks again @sefeg, really great update will come with this new system.

Cheers,
@artfisica

**Comment by sefeg** [comment]
Thank you both for the positive feedback and the productive discussions.
