### ISSUE TITLE
ssl: get and install certificates

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1333]
Get multi-domain SSL certificate for PROD, DEV, QA like we did for CAP.

Install them both on OpenShift and Puppet.

**Comment by tiborsimko** [comment]
Cannot launch with our our HTTPS on central PaaS platform...

**Comment by cbourjau** [comment]
I am hitting an issue downloading ALICE files [1] through the HTTP gateway. The problem is that the library I'm using does not allow to bypass invalid certificates. Will the issue discussed here also add valid certificates for the data downloads? 
Cheers!

[1] https://eospublichttp05.cern.ch/eos/opendata/alice/2010/LHC10h/000139038/ESD/0003/AliESDs.root

**Comment by tiborsimko** [comment]
@cbourjau Please note that we had installed the redirector to support the old URLs of the form:

```
     http://opendata.cern.ch//eos/opendata/alice/...
```
   
so that the old technique would still work:

```console
$ wget http://opendata.cern.ch//eos/opendata/alice/2010/LHC10h/000139038/ESD/0003/AliESDs.root
[...]
2018-04-04 14:47:59 (23.2 MB/s) - ‘AliESDs.root’ saved [376822741/376822741]
```

**Comment by tiborsimko** [comment]
Closing since we cannot use "private domain" certificates with the central PaaS platform.

**Comment by mvidalgarcia** [comment]
[Let's Encrypt](https://letsencrypt.org/) certificates added to all opendata.cern.ch instances:
- https://opendata.cern.ch
- https://opendata-qa.cern.ch
- https://opendata-dev.cern.ch
