### ISSUE TITLE
templates: /research/cms

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1375]
Implement http://opendata.cern.ch/research/CMS

- case 3 - Collection
- Note: There needs to be a view for each experiment, which will replace the current /education/string:exp and /research/string:exp. So eventually there will be a CMS Collection (for example), but not a /research/CMS Collection.

**Comment by tiborsimko** [comment]
But the old URLs need to be preserved, so one "collection page" wouldn't be enough, because we show some content and some not depending on education-context or research-context.

Moreover, the "teaser boxes" about VMs and getting started are displayed depending on the context...

**Comment by daslerr** [comment]
@tiborsimko Would you agree to having `/education` and `/research` point to all resources (the default search) and each of the sub-URLs point to the appropriate facet (i.e. `/education/alice` points to faceted results for all resources tagged ALICE) just for the sake of maintaining the old URLs? 

Otherwise it seems to me we'd have to add Education and Research into the records as tags, which seems like unnecessary work if we're going to eventually use more specific facets instead. This would also reverse our decisions from previous meetings, where we said that these were not useful tags because of their generality, and where we established that there was no longer a need to have separate research and education contexts. 

For the record, my preference would actually be to just eliminate the `/research` and `/education` URL paths. I still disagree about the need to preserve the old URLs, since they no longer accurately represent the underlying structure of the information and since I think we should be more concerned about preserving the content of the site rather than its presentation. But I may be outvoted in this.

**Comment by tiborsimko** [comment]
@daslerr Yes, pointing to a faceted search would be more than enough here, combined with creating featured articles if experiments want to advertise some edu/res content better.

Regarding elimination, I agree that preserving record content is obviously a must 😄 i.e. it is a given. Preserving old IA links (such as `/education`) to point to some new suitable IA endpoints (such as concrete faceted search) is also necessary in my eyes; much better than displaying 404 pages. It's not much additional work anyway...
