### ISSUE TITLE
templates: "Explore datasets"

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1420]
Following up #1415, we have three kinds of datasets in the system. We should now amend the page header menu "Explore datasets" accordingly.

**Comment by ioannistsanaktsidis** [comment]
Not quite clear what is needed in this one. Should we change the name from ```Explore``` to ```Explore datasets``` ?

**Comment by daslerr** [comment]
I understand this to mean that under the `Explore` header we should list each of the different kinds of datasets instead of just `datasets`.

**Comment by ioannistsanaktsidis** [comment]
Ok, so sth like 
```Primary Dataset
      Derived Dataset 
      Collision Data ```

**Comment by ioannistsanaktsidis** [comment]
So to finalise and close also this one, @tiborsimko what is your proposal ? Should we replace
```
Explore > Datasets
```
to 
```
Explore >      Primary Dataset
                      Derived Dataset 
                      Collision Data 
```
?

**Comment by katilp** [comment]
@ioannistsanaktsidis NB, for us, Primary dataset = Collision data, you should add Simulated datasets

**Comment by ioannistsanaktsidis** [comment]
cc @daslerr

**Comment by daslerr** [comment]
Change it to:
```
Explore > Datasets
          News
          Documentation
          Software
``` 

I do think that @tiborsimko was suggesting to add `primary dataset` etc. to the `Explore` menu, but that menu isn't just for datasets. The `Explore` menu is supposed to reflect the different types of records we have, but the categories for those have changed since we first proposed the menu. The `Explore` menu should now point to `Datasets`, `News`, `Documentation`, and `Software`. (`Glossary` isn't included because it's under `About` as it was on the old site.) If we were to update the `Explore` menu with exploded dataset categories, then we would have to do that with all the other record types, which would make the menu too long. To get this done, let's just change it to reflect the new top-level record types. If necessary, we can have a discussion later about breaking out the header menu into types instead of grouping everything under `Explore`.
