### ISSUE TITLE
UI: implement new homepage

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernopendata/opendata.cern.ch#1477]
After the discussions that we had today I refactored a bit the current test design. 
Here is a gif so as to check it.
![opendata](https://user-images.githubusercontent.com/7301890/31340783-8e389236-ad07-11e7-8f38-7373dabbe02a.gif)
Generally after some discussions that we had with @tiborsimko we need to decide if we are actually going for this design or we keep the same old COD2 style as we had it before. 
Please everyone share your opinion so as I can proceed in implementing the new UI or revert back to the old one. Many thanks!

**Comment by annatrz** [comment]
i like it a lot, maybe we could make the graphic at the top even smaller, so we can see bigger part of the news boxes. And nice labels ^^

**Comment by suenjedt** [comment]
Great! I think that nicely combines the new design with the new IA (cf wireframes). Lets discuss with @daslerr or @sefeg (and everyone else of course) when we could schedule best a testing sprint.

**Comment by tiborsimko** [comment]
The new UI is visually appealing and I'm all for going for it -- especially now with the story images in the latest version 😄 -- provided we are ready for some additional design work to match the new IA.

As mentioned in the chat, the most important issues at hand in my eyes are (a) actionable page body to advertise the most popular functionality very prominently (e.g. permanently featured "education" box about event displays? e.g. permanently featured "research" blog story about CMS VMS analyses?) in order to engage our various kinds of end users in a seamless way right after hitting the home page; (b) the new COD3 logo that appeared here as a sort of "by product" of the UI change only, but that would a very visible graphical identity change in itself (e.g. do we want to go into designing and selecting a new COD3 logo now? e.g. do we want to rebrush the COD2 logo slightly to fit the new style? etc). If you are ready to attack them both from the design perspective, then I'd say let's go for it and call the kick-off! 

The best in my eyes would be to list everything that needs to be done in order to deliver the new UI for prime time, i.e. what remains to be done from the IA/UX modelling perspective (e.g. featured edu/res stories?), from the UI graphics style designing perspective (e.g. logo?), and from the implementation perspective (e.g. mobile CSS?), so that we have a comprehensive list of tasks to match what is feasible within our time frame, skill and budget set, and we can see who drives what.

We can create such list together during the kick-off...

**Comment by suenjedt** [comment]
@tiborsimko how do we plan to tackle this design work? @pamfilos do you feel comfortable tackling the design tasks mentioned above or do we need to identify external expertise?

**Comment by sefeg** [comment]
I think it looks really great. And it nicely implements the new IA (wireframes).

Depending on how important the search bar is for (expert) users, we could consider placing it on the top image (see: https://www.ebi.ac.uk/). That would also allow us to show a few search examples like one can see on the linked page. Tests (especially with researchers) should reveal whether or not we should place the search bar more prominently.

**Comment by ioannistsanaktsidis** [comment]
And a small  update, here is a fist version of search results:
![search_results](https://user-images.githubusercontent.com/7301890/31388704-25d5a56c-adcf-11e7-9be6-1b2226c1f38a.gif)

just to showcase them in a nice way for any kind of demo.

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis Nice! If we decide to kick this off, then let's put the "new-ui" branch directly on the "master" branch so that anyone can easily see it.

@suenjedt The most visible (and hardest) design decisions are the ones I highlighted above. Otherwise we should be able to tackle the rest relatively smoothly. (We would document the rest during the kick-off.) @ioannistsanaktsidis @pamfilos? ready to kick-off some design work?

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko yes , I am making some changes right now so as to put the new-ui branch to master. By today everything should be ready. I can ping you before the merging :)

**Comment by sefeg** [comment]
Great! And then once it is on -dev, we can plan the first user tests.

**Comment by ioannistsanaktsidis** [comment]
Closing this as already implemented and the concerns of people have moved to separate issues accordingly!
