### ISSUE TITLE
UI: add images to the news records

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernopendata/opendata.cern.ch#1483]
We need to decide if we need images for the new design so  as to add them to the news records.
IMO either we should find really nice ones that fit the new minimalistic style, or not to add them at all.

**Comment by sefeg** [comment]
We could also think about adding images only to a few selected records, where we have suitable images available. That would also give us the opportunity to highlight / feature some records. A quick sketch of how this could look like:

![landing-page-boxes](https://user-images.githubusercontent.com/25487025/31495754-2248116a-af59-11e7-9787-983e9fcb875b.png)

**Comment by ioannistsanaktsidis** [comment]
What about this one ? I am going to move it to the COD3-UI milestone (general one) as we just need to attach the correct images to the feature records.

**Comment by sefeg** [comment]
Agreed! I think that it could be nice to design for a little more flexibility in a sense that we could feature more than just one record with an image (in situations where we have several very interesting records with image materials on the landing page). I will depict my idea in a sketch later.

**Comment by suenjedt** [comment]
@sefeg please also collect a few image selections. thanks

**Comment by tiborsimko** [comment]
The images work best if they are very specific to the story that is being featured in the box. I.e. they should be very specific with respect to each promoted content, rather than being only "nice to the eye".

For example, if the featured article talks about how to use CMS VM to make an example analysis, then one can use the screenshot of the final plot, or a screenshot of the VM environment with running code.

For example, if the featured article presents the new OPERA open data release, then one can use a screenshot of one event display from that release. 

We can always work very closely with the authors of the featured pieces in order to have nice supportive illustrations. 

(At a risk of stating the obvious 😉 I see it quite the same as a newspaper would use first-page pictures to promote the top articles; sometimes the illustrations might be generic, but more often then not they are very specific to the given featured conent, providing supporting visual illustration clues to attract the eye immediately to the right spot. People hear about event displays on COD, they go to the homepage, and bang, they see it right there featuring the event display facility or a detailed article about it.)

**Comment by tiborsimko** [comment]
> We could also think about adding images only to a few selected records, where we have suitable images available.

Dunno how such a mix-up would look... We could simply promote 3-4 stories max and always use some images for them. The number of story/guide/documentation authors is quite well limited, so it should work. (And for other items, there can be a simple "see more..." link at the end bringing to theh usual search.)

**Comment by sefeg** [comment]
@tiborsimko I completely agree when it comes to the image selection. Our previous experience in designing the mockup also suggests that we most likely not select suitable images in the eyes of physicists. We can of course always try to find a suitable image [here](https://press.cern/multimedia/photos-images) (@suenjedt), but I also think that the selection should be very closely related to the actual analysis and should ideally be proposed by the physicist.

**Comment by sefeg** [comment]
> Dunno how such a mix-up would look... We could simply promote 3-4 stories max and always use some images for them. The number of story/guide/documentation authors is quite well limited, so it should work. (And for other items, there can be a simple "see more..." link at the end bringing to theh usual search.)

That sounds similar to what I proposed in the sketch before (where exactly one record is assigned an image). As show in the following, one could be a bit more flexible by replacing an image-record with e.g. three simple records (or vice versa). That would give us some more flexibility.

![image](https://user-images.githubusercontent.com/25487025/31770797-c487d9c6-b4d9-11e7-887b-6782d94c51d0.png)

**Comment by sefeg** [comment]
Concerning my proposal above, consensus seems to be that at this point we don't have to develop anything that supports "converting" image-featured article space to multiple non-image blocks (or vice versa), but that instead we stick with our current system that requires an image for every record featured on the landing page.

In case we see need for that in the future (e.g. a lot of interesting records popping up that don't have a meaningful image; or we see the need to feature many more than six records on the landing page), we can go back to the proposal.

Will leave the issue open because actually adding images has not yet been implemented. It is only a placeholder on -dev so far.

**Comment by tiborsimko** [comment]
> Concerning my proposal above, consensus seems to be that at this point we don't have to develop anything that supports "converting" image-featured article space to multiple non-image blocks (or vice versa), but that instead we stick with our current system that requires an image for every record featured on the landing page.

👍 

I have created a separate issue #1729 to implement the feature.  In this issue we can muse further (1) which articles to feature, (2) in which order, and (3) what are their best illustrative screenshots. @sefeg @daslerr would you like to propose a list?

**Comment by sefeg** [comment]
I created a dedicated issue to discuss the six articles that we feature for the release: #1732 

Since the implementation moved to #1729 and we agreed to postpone the above design considerations, I close this issue for now
