### ISSUE TITLE
search: investigate facet order

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1659]
Investigate an appropriate facet display order for the search results pages that would be appropriate  to the user from the UX perspective.

Currently, the facets are displayed alphabetically:

- Filter by collision energy
- Filter by collision type
- Filter by experiment
- Filter by file type
- Filter by keywords
- Filter by topic category
- Filter by type
- Filter by year

We may want to show the most important ones first, i.e. the type/subtype first, especially now that the collection concept is not advertised anymore (and that dataset/software/etc facets could basically serve that navigational purposes).

**Comment by katilp** [comment]
I agree, I would start by either Filter by type or Filter by experiment.
The MC category search should be right after Filter by type. 
Can the Filter categories be displayed so that only the title is visible and the user can expand it to see the choice?

**Comment by sefeg** [comment]
I definitely agree that we should start with Type (Dataset, Documentation, ...) and Experiment on the top, because they are the most generally understandable (high-level) categories we have. Especially if we think about the general public that knows what a Guide is, but not what an ig file type is. Also, as mentioned, our UX experience is based on the record types. After a user selected e.g. Explore -> Dataset, we should provide a clear and immediately visible feedback, that she or he got to the desired location. The best way to do that is to show the Type facet category first and select the corresponding checkbox.

**Comment by daslerr** [comment]
From our testing this afternoon, I can confirm that starting the list of filters with Type and Experiment is the best way to go, since these match information from the header menu and give the user confirmation that they have arrived in the right place when browsing. The order for the other categories is less important from a navigation confirmation perspective, so we can defer to the physicists for any order preference for those.
