### ISSUE TITLE
search: investigate facet value order

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1660]
Investigate an appropriate facet value order inside each individual facet.

Currently, they are displayed by value count, for example:

- Filter by type
   - Supplementaries 1496 +
   - Dataset 1413 +
   - Documentation 30 + 
   - ...

We may want to keep it like this, or order them othewise, for example alphabetically, or by perceived 
subtype importance, etc. 

This can be especially apparent in the year facet:

- Filter by year
   - 2011 1950
   - 2012 906
   - 2010 875
   - 2016 12

where the current order may not be very intuitive.  (We could introduce e.g. graphical representation, here, but that's a bit out of scope right now... and we should check other facets, this was just an example.)

This can be again user-tested...

**Comment by sefeg** [comment]
We discussed this and agreed to order **alphabetically**. That resolves obvious issues (e.g. related to the year) and even leads to a meaningful order in the record **type** filter. Since we also agreed to re-calculate the numbers based on the active selection ( #1685 ), an ordering mechanism based on the count would lead to continuously changing element orders and would thus confuse users.
