### ISSUE TITLE
Keyword "display" for Event display files? Or ig -> ig (event display) in file type.

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1782]
Can we have the keyword "display" for event display files, or then just add (event display) after ig in the search menu so that even non experts would easily find these files?

**Comment by tiborsimko** [comment]
The file extension is `.ig`, so it seems good to keep it like that literally in my eyes.

I'd rather prefer using the "keyword" field, or perhaps break down the "type" values "Dataset > Derived" to better distinguish between various "derived" datasets (PAT tuples, event display files...), or perhaps use `files.type` field.

However, and more importantly, isn't it enough if people search for the words "event display" from the start?

- http://opendata-dev.web.cern.ch/search?page=1&size=20&q=event%20display

They will find these records nicely already... and we don't need to add any extra keywords etc.

Basically, the function of facets is to help out navigating in the search results sea.  But this search result sea is usually started by an appropriate search query that people are interested at... Perhaps this feedback finding points to an UX issue where our search box is located too far from the facets, making it harder to see how to refine the results by *altering the query string*, and not *altering the facet values*.  In other words, if people start with an empty search, and they don't alter the search query string and only use facets, I'm afraid that we won't be able to easily satisfy all the various narrowing results needs by populating the keywords or other fields... since different people will have different navigation needs. Hence we can perhaps better guide users that there is *also* a possibility to refine search by altering the query string, based on any free text they may be interested exploring, and not using only facets? @daslerr @sefeg Is this something you have observed during user tests?

**Comment by sefeg** [comment]
I think that our perception that "only" facets are used for searching are biased because we have been testing them a lot like this in the last few weeks. In practice, we have not seen anyone who clicked on the search button without specifying any search query. And I would not expect this to be a typical behavior. Asking users to find e.g. "<collaboration> guides", most intuitively typed the whole string into the search bar or just searched for "<collaboration>". We got used to search engines showing us what we want to find. We could possibly think about showing the search string close to the information how many results have been found. E.g. _Found 2031 results. Your search: CMS._ That would contribute to a positiv visibility of system status.

**Comment by katilp** [comment]
@tiborsimko  for this use case the search fails  http://opendata-dev.web.cern.ch/search?page=1&size=20&q=event%20display  returns more than 400 files for CMS only as it takes some MC as well (event is a very generic word...). I have a feeling that any "complex" (i.e. more than one word) search may turn out to be unstable in the future as we add records from different sources, that is why I would prefer a keyword.

**Comment by katilp** [comment]
It is however true that  searching display only returns what is needed http://opendata-dev.web.cern.ch/search?page=1&size=20&q=display as well as "event display"
http://opendata-dev.web.cern.ch/search?page=1&size=20&q=%22event%20display%22

**Comment by katilp** [comment]
Can we close this? The original issues has been addressed.
