### ISSUE TITLE
Assigning "education" keyword to applicable resources

### ISSUE THREAD

**Issue by sefeg** [cernopendata/opendata.cern.ch#1790]
When we wanted to link to educational resources on COD3, we realized that simply linking to "Guide" is not sufficient, as also resources are associated that are not suitable for educational purposes (e.g. VM related guides). The idea is to introduce a keyword called **education**. We have to decide which resources should be associated to an **education** keyword.

My initial thoughts on CMS resources: 
- All CMS Learning resources
- [Guide to education use of CMS data](http://opendata-dev.web.cern.ch/articles/cms-guide-to-education-use-of-cms-open-data)
- [Video tutorial for Outreach Exercise 2010](http://opendata-dev.web.cern.ch/record/55)
- [Explore CMS open data and play with the histograms - Help](http://opendata-dev.web.cern.ch/record/57)
- [Explore CMS open data and visualise detector events - Help](http://opendata-dev.web.cern.ch/record/58)
- [Worksheets and instructions for schools prepared during the High School Teacher Programme 2016](http://opendata-dev.web.cern.ch/record/72)

This is just a start. @katilp please feel free to add any CMS resource that you think should be associated with an **education** keyword

**Comment by katilp** [comment]
Thanks @sefeg!
The new records I've propose recently are all education. @tiborsimko Where does the keyword go in json see e.g. #1760 #1761 #1762 #1789

**Comment by tiborsimko** [comment]
@katilp Regarding the addition of the education keyword to the existing COD2 records, we can best do it in an automated wa: it would be enough if you construct a list of wanted record IDs, such as `55 58 72 ...`, and I'll automatise the addition afterwards. This can then be used as an example for writing new COD3 records.

**Comment by katilp** [comment]
@RaoOfPhysics @sefeg @tiborsimko We have education records at university level and at school level, to my view (as I'm working often with high-school teachers) it would be useful to differentiate.
Can we have "education" (can cover all education), and then "school" as an additional keyword?
That would give:
education: http://opendata-dev.web.cern.ch/articles/cms-guide-to-education-use-of-cms-open-data  
50 53 54 61 51 52 57 58 72
school: http://opendata-dev.web.cern.ch/articles/cms-guide-to-education-use-of-cms-open-data
53 57 72 and all the new records #1789 #1760 #1761 #1762

**Comment by RaoOfPhysics** [comment]
I think it would be helpful to distinguish between the target groups' levels.

**Comment by tiborsimko** [comment]
@ArtemisLav Related to the keyword enrichment task, we currently have:

![keywords](https://user-images.githubusercontent.com/517546/33021356-e08173e4-ce01-11e7-84e2-e4a4ce6ddca0.png)

Let's take advantage and standardise the values here.  I'd vote for using "masterclass" everywhere in place of "masterclasses".

**Comment by tiborsimko** [comment]
> Can we have "education" (can cover all education), and then "school" as an additional keyword?

OK. @ArtemisLav Shall we go for "school" or "high-school"?

**Comment by ArtemisLav** [comment]
For me, "high-school" would make more sense, since "school" does not mean the same thing everywhere (in some places it is used for primary-secondary education only and in others for all educational levels), so its meaning wouldn't be completely clear.

**Comment by RaoOfPhysics** [comment]
Yeah, this is tricky. Some exercises might also be done with middle-school students. And there is "grad school". But I think "high school" is good.

**Comment by katilp** [comment]
Careful though, we may have material adapted for earlier grades as well (i.e. event display, the material in preparation for use Finland). In English terms though school in generic, isn't it?

**Comment by daslerr** [comment]
To me, there's not a big enough difference between "education" and "school" as keywords for the distinction to be immediately obvious. For my version of English, "school" is generic, but it's almost too generic, because it's not necessarily limited to secondary and below. It's common for people who talk like me to say "when I was in school" and really mean when they were at university. This might be a US-centric viewpoint, though.

**Comment by ArtemisLav** [comment]
We kind of had this conversation previously, when we were talking about tagging materials as "beginner", "advanced" and so on. It _is_ tricky, which is why we ended up dropping that, but if you think it would be useful, let's go for it it. 

However, if we want to avoid the confusion with "school", we would then need more than one keyword to cover all the possible educational levels (high school, middle school, etc.), and we would need to make sure that the terms are more or less universally understood (i.e. in the US/UK/EU etc.).

**Comment by katilp** [comment]
But if I were a teacher, I would be more than happy to have a keyword school... it clearly indicates that the level for the material is right while with "beginner", "advanced" it could also indicate a "beginner" in research side

**Comment by daslerr** [comment]
I agree that "beginner" and "advanced" aren't clear enough about at what the person is a beginner, so I think some kind of education-specific distinction makes sense. In the US, we still say "primary education" and "secondary education", so if that's also used in the UK/EU, then that could be a good thing to use.

**Comment by katilp** [comment]
That's long for a keyword.... and non-native speakers would be lost with primary/secondary. Could we just go simple? No choice is perfect, so we could as well take what is the easiest... For the moment, I would not separate "middle" or "high" school, the entries for the school stuff in general are not so many and the teachers can do it themselves.

**Comment by tiborsimko** [comment]
FWIW the original PR that I prepared (#1834) uses a simple "school" already... The proper naming is hard 😄 but can be easily changed based on consensus. 

As for me, I agree that "primary/secondary education" would be kind of long and too official-sounding, and I also think that "education" and "school" may be confusing... What about keeping "education" and going for "teachers" or "teaching" instead of "school"? It would indicate both the HST connection and that the record in question is especially suitable for teachers and teaching purposes... Would it work? Just trying to muse out loud about possible compromise names...

**Comment by katilp** [comment]
"teachers" or "teaching" would fit very well, it is certainly a keyword which teachers would easily pick 😄

**Comment by ArtemisLav** [comment]
"teaching" looks okay to me. @sefeg @daslerr ?

**Comment by tiborsimko** [comment]
https://github.com/cernopendata/opendata.cern.ch/pull/1834 updated to "teaching".

**Comment by daslerr** [comment]
@tiborsimko @katilp Can this be closed now after #1834? Or do the "education" and "teaching" keywords still need to be added to certain records?

**Comment by katilp** [comment]
I thinks it is OK ad can be closed
