### ISSUE TITLE
events: `/visualise/events/cms` does not load files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1839]
The standalone event display does not work on COD3.

**Comment by tpmccauley** [comment]
I assume this is a problem with files not loading? It looks like at least for one record I tried there is no file to load. http://opendata-dev.web.cern.ch/record/615/files/ gives me a "page not found"

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley indeed there are no files loaded due to some loading-time issues that we have. My question is about this part. 
<img width="686" alt="screen shot 2017-11-20 at 16 37 31" src="https://user-images.githubusercontent.com/7301890/33026585-102aa52a-ce11-11e7-9e87-b0089504a5ad.png">

where it tries to fetch the files from record -1 ?
 
![screen shot 2017-11-20 at 16 39 06](https://user-images.githubusercontent.com/7301890/33026696-4b5d09bc-ce11-11e7-9073-7b521d0f5725.png)

**Comment by tpmccauley** [comment]
@tiborsimko that is a placeholder for the new event display files mentioned here https://github.com/cernopendata/opendata.cern.ch/issues/1404 which need to be uploaded and receive record numbers

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley  nice, also regards on loading the previewer in the record itself, which function we should call and pass the file ? Is it https://github.com/cms-outreach/ispy-webgl/blob/cod3/js/files-load.js#L390 ?

**Comment by tpmccauley** [comment]
That's it. Yes @ioannistsanaktsidis

**Comment by tiborsimko** [comment]
> @tiborsimko that is a placeholder for the new event display files mentioned here #1404 which need to be uploaded and receive record numbers

We'll upload them as part of the COD3-Beta sprint.  However I was trying to display some old 2010 files with the standalone previewer and it wasn't working either?

**Comment by ioannistsanaktsidis** [comment]
Closing as problem solved.
