### ISSUE TITLE
Correction to record 5000 (Analysis code...)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1856]
Corrections to http://opendata-qa.web.cern.ch/record/5000:
- dio link does not work
- typo: DoebleElectron -> DoubleElectron (x 2)
- list the datasets (links) with a line break (under Use with)
- @katilp checking with @zenaiev if this should be under "Analysis" and not "Validation"
- link after System details is wrong: should be to record 252 (now 249)
- remove the sentence "Then install and run the Demo (demo analyzer) program following the instructions at How to Test & Validate." under "How can you use this?"

**Comment by katilp** [comment]
Checked with Achim, this should under "Software" category, and "Analysis" subcategory, so the Collection: CMS-Validation-Utilities should be changed as well.

@tiborsimko this is an example case where the collections, as we are not showing them any more on portal, may become problematic especially for software items. For example, a software record can be both Analysis and Validation, and this can be nicely handled now with subcategories, but not with the earlier collections.
For datasets though they are quite clear.

**Comment by katilp** [comment]
Add subtitles under "Use with",

- Data (followed by the three collision data records that are already there)
- Monte Carlo, add the following list

   - TTJets_TuneZ2_7TeV-madgraph-tauola record 1544
   - T_TuneZ2_tW-channel-DR_7TeV-powheg-tauola 1638
   - tW-channel-DR_7TeV-powheg-tauola checking with @zenaiev
   - WJetsToLNu_TuneZ2_7TeV-madgraph-tauola 1633
   - DYJetsToLL_M-10To50_TuneZ2_7TeV-pythia6 1393
   - DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola 1395

**Comment by tiborsimko** [comment]
@katilp Regarding collections, we try to "hide" this concept in COD3, and prefer to use types instead... so collections are there mostly for old links so that they would return something suitable.  But the new links in the COD3 style won't use collections at all... so perhaps it won't be even necessary to add collections to new records after some time...

**Comment by katilp** [comment]
@tiborsimko OK, for the moment it is shown quite prominently after the title in  http://opendata-qa.web.cern.ch/record/5000 (Collection: CMS-Validation-Utilities) but if this is removed then it's all fine

**Comment by katilp** [comment]
If I open the zip file from github in record 5000, and extract I see the following:
![zip](https://user-images.githubusercontent.com/5859918/33123285-11c9e750-cf7a-11e7-8bd5-a7e28e4caf9c.PNG)

The first directory is what I would expect, what is all the rest?

**Comment by ArtemisLav** [comment]
@katilp which link are you referring to? For me, everything works.

Regarding the `use_with` property, the schema does not allow such a structure (i.e. we can have only one  instance with one description and links), so right now I can only add the MC datasets to the list with the collision datasets. @tiborsimko is there another way to do this, so that it can be displayed as indicated above?

**Comment by katilp** [comment]
@ArtemisLav If I click on http://doi.org/10.7483/OPENDATA.CMS.TTGV.3IKL after DOI I get
![doi](https://user-images.githubusercontent.com/5859918/33135836-d9a3ff58-cfa3-11e7-85f5-ea3398761656.PNG)

For the dataset list, we may need to consider the possibility for adding subtitles. The analysis examples will get more complex and involve more datasets so it would be very useful for the sake of clarity. But for the moment, single list is fine, to get started

**Comment by ArtemisLav** [comment]
Ah, OK, no, this is fine, it just means that the DOI is not active yet. What I do is I "reserve" a DOI to add to the records. I only activate/register the DOIs with DataCite once the records are published, so we should only be worried if we see inactive DOI links in published records. 

For the datasets, perhaps for now we could just amend the description a bit in the "Use with" section, so that the MC additions make more sense? Just let me know if you would like me to modify that.

**Comment by katilp** [comment]
OK, fine then. Can you add some text in the "Use with" section before the list? But not in the middle of the list?

**Comment by ArtemisLav** [comment]
Yes, I can amend the part that now reads "Use this with 2011 DoebleElectron, DoubleMuon and MuEG primary dataset (see detailed instructions in readme files and code)."

**Comment by katilp** [comment]
OK, let's have there: 

"Use this with 2011 DoubleElectron, DoubleMuon and MuEG collision datasets and the simulated datasets listed below (see the detailed instructions in the readme files and code)." 

And then the full list (starting with DoubleElectron, DoubleMuon and MuEG and the MC files.
