### ISSUE TITLE
New homepage implementation (changes to design and organization)

### ISSUE THREAD

**Issue by daslerr** [cernopendata/opendata.cern.ch#1940]
This summarizes what we discussed yesterday about changing the organization of the homepage and includes the specific articles to link to in the various sections.  

TOP
(Conceptually, the "records" section.)
- [x] Large, prominent search bar. 
- [x] Links to the record categories and experimental groups underneath search bar to prompt users for the kinds of things they can search for. Links direct to search results pages for those categories. (ex: Dataset, Software, CMS, ATLAS...)
- [x] Change "1 PB" to "1 petabyte"

MIDDLE 
(Conceptually, the "stuff to read" section.)
First box: Title = "Learn". 
- [ ] /articles/welcome-to-our-updated-portal
- [ ] /articles/cms-guide-to-education-use-of-cms-open-data
- [ ] /articles/improving-educational-content-with-high-school-teachers-a-field-report-from-our-summer-students
- [ ] /glossary
- [ ] More link points to search results for Documentation

Second box: Title = "Visualise". 
- [ ] /visualise/events/cms
- [ ] /visualise/events/opera
- [ ] /visualise/histograms/cms

Third box: Title = "Analyse". 
- [ ] /articles/cms-guide-to-research-use-of-cms-open-data
- [ ] /articles/atlas-higgs-machine-learning-challenge
- [ ] /articles/getting-started-with-lhcb-open-data
- [ ] /articles/getting-started-with-alice-open-data
- [ ] More link points to the same set of search results the old /research URL now points to

BOTTOM
(Conceptually, the "fun/extra stuff" section.)
- [x] News. Retain the most recent news implementation of @ioannistsanaktsidis with the brief stacked boxes, but remove all pictures.

**Comment by katilp** [comment]
Very nice! 
Can the CMS release update be featured the "learn" box of the middle section?
We would also give priority there to the article form the MIT group over the summer student report.

Just a note: the other experiments do not yet release research quality data, so some care for misunderstandings under "Analyse". @RaoOfPhysics what do you think?

**Comment by suenjedt** [comment]
Great - sounds convincing and I note the improved terminology

**Comment by RaoOfPhysics** [comment]
> Just a note: the other experiments do not yet release research quality data, so some care for misunderstandings under "Analyse".

FWIW, I echo @katilp's concerns.

Otherwise, good stuff, @daslerr. Looking forward to seeing the mockup. :)

**Comment by pamfilos** [comment]
![opendata_desktop3](https://user-images.githubusercontent.com/6625469/33373190-0a6cd4a4-d501-11e7-959b-5fdae4a2cf3d.jpg)

![opendata_desktop1](https://user-images.githubusercontent.com/6625469/33373206-1d9f8904-d501-11e7-815a-7940d9f094a7.jpg)

**Comment by annatrz** [comment]
looks really nice!

**Comment by ioannistsanaktsidis** [comment]
I think it covers exactly what we discussed altogether :)

**Comment by katilp** [comment]
Looks great! Two small remarks on details :
- "supplementary material" should not be exposed under "Explore", it contains material which has very little meaning if not linked in context (they are linked through datasets and that where they will be accessed)
- I guess that the items exposed are preliminary, but take note that we do not necessarily want to highlight Analysis framework for HEP tutorial under "Analyse" as it is something that we consider rather "external"

**Comment by ArtemisLav** [comment]
It looks fantastic! Just a very minor comment: perhaps we could have something else instead of "focus on".

**Comment by tiborsimko** [comment]
Nicely captures the concept we drafted on paper :smile: Some remarks:

- "Explore more than **"1 petabyte** ..." spelled like this, will PB in full, will have better visual impact here.

- The search example "getting started" is better left alone, i.e. separated from "experiment:cms", since getting started is something that is searched by novices, who wouldn't use fielded search.  And, for power users, instead of "experiment:cms", we can advertise something like "energy:7TeV", since experiments are linked down below in the focus area already.

- Regarding the use of light grey, please think of using good contrast colours, e.g. datasets/software links look a bit too light in the mock-up. (Recall the COD2 feedback from visually impaired users.)

- The leading illustrative pictures for Learn-Visualise-Analyse are somehow dissonant in style, some look flat, some scattered, some 3D-like... Would you be able to find illustrations of more similar style from the original design stack? 

- After the L-V-A page is transformed into a real web page, if there will be too much of free space, then we could think of enlarging L-V-A titles and introducing one catch phrase under each title to introduce what the collection of links below will be. Something like:
  - Learn // Discover the particle physics open data world
  - Visualise // Explore detector events and run basic histogramming
  - Analyse // Start virtual machines and run your own physics analyses
  Just some phrases for illustration... I wanted to raise this possibility now, in case it will help with designing presentation of the boxes. We'll see IRL.
    
- No leading illustrative picture for News-and-Updates? Might be nice to have one for consistency .

**Comment by pamfilos** [comment]
FYI
 - for wordings and various texts, I just used what was scribbled on paper yesterday. We just need to have a list of them and I will adapt it ( please add on the first comment )

- same for search example, I just added it for a more advanced example of search, which i think it is nice to have ( please also add search examples on first comment - for now I will add ```energy:7TeV```)

- Regarding colors: We can sit all together on the Friday meeting and decide about the colors (easiest thing is to make everything black and white like official CERN site - no contrast issues )

- Regarding illustrations: I just got the ones we had from Eammon's design. If anybody has some suggestion please provide also ( have in mind that they should be of the same style - meaning they should look good together, and rest of portal)

- OK for sub-titles . IMHO I think it would be too much to add more content, since on smaller screens as is it will look ok, but with more content we would have placement issues (but we can recheck when prototype is on DEV)

- Again, IMHO I like it clean, since it's going to be something like a banner with news, nothing else is needed. But, same as point 4, provided the illustrations we can try it

**Comment by tiborsimko** [comment]
@suenjedt I meant the various logo-like graphic illustrations that Eamonn had in his design document deck, such as the "unversity hat" or the "interconnected network blob"; @ioannistsanaktsidis briefly showed them on his laptop yesterday. I think we should be able to find there three similar ones that we could use for the L-V-A illustration purposes, and that would be also more look-alike in the same flat-like 2D-like style... which would give a more consistent, nicer look.

(We could also explore icons8.com that we used for the Invenio home page; but I think there should be enough ready-to-be-used ones in Eamonn's deck.)

**Comment by daslerr** [comment]
I agree with the 1 PB vs. 1 petabyte suggestion, so I've updated the first comment with that. 

I agree with @pamfilos that adding subtitles seems like too much for the boxes, so I didn't add anything about those. I also agree about not needing a leading illustration for news. 

For the "focus on" suggestion by @ArtemisLav, I'm not sure what to change it to. If we want to stick with a verb, "generated by" would be descriptive, but I don't know that I like it better. (Then it also kind of makes a sentence, e.g. "Explore software generated by ATLAS." I'm not clear whether that's a good thing. :) ) Otherwise, if we're not settled on verbs, "experiments" seems to be the most common word people use, but it's not super catchy. @RaoOfPhysics, as a communications guy, do you have any suggestions?

**Comment by RaoOfPhysics** [comment]
I agree that a verb is ideal, given the rest of the "do words" on the page. If we were to change:

- "Explore" &rarr; "Find"
- "Focus on" &rarr; "Explore"

that might work. I've spent a while considering options and going through a thesaurus, and this makes the most sense to me. "Find" does have thematic overlap with "Search", though.

What do others think?

**Comment by tiborsimko** [comment]
>  "Find" does have thematic overlap with "Search", though.

Indeed, that's what I feel as well... Besides, we are not "exploring CMS" as it were, only narrowing down our own content... I like more "explore" on the left and "focus" on the right.

> I also agree about not needing a leading illustration for news.

I like consistency, so if the other three bxes have leading illustrative graphics, why not the fourth? Better have them all, or remove them all... Anyway, regrding this and regaring the possible catch phrases, we shall see better how it fits when there is a real prototype.

**Comment by daslerr** [comment]
Thanks for the word investigation, everyone. For the sake of simplicity and efficiency, let's just stick with "explore" and "focus on". If it seems to cause users problems, we can change.

**Comment by tiborsimko** [comment]
New homepage organisation is fully implemented; closing.  Let's deal with remaining issues (final selection of links, final style prettification) in subsequent issues.
