### ISSUE TITLE
Fixes to new homepage

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#2020]
The about drop down is partially outside the screen

<img width="138" alt="screen shot 2017-12-04 at 4 37 09 pm" src="https://user-images.githubusercontent.com/7300319/33564997-32bc7152-d91c-11e7-8c6b-225a90f2b155.png">

The boxes are not aligned. Font should be bigger. Reduce white space around boxes (probably comes with alignment). 
<img width="1251" alt="screen shot 2017-12-04 at 4 36 53 pm" src="https://user-images.githubusercontent.com/7300319/33565083-738104b4-d91c-11e7-97a0-98b0730f2e13.png">

(Sorry for rough wording, am travelling)

**Comment by RaoOfPhysics** [comment]
See also #722.

**Comment by RaoOfPhysics** [comment]
- [ ] Can we change the text to "Explore more than **1 petabyte** of open data from particle physics!" &larr; note the lack of space between the last word and the exclamation mark.
- [ ] The word "Search" is repeated both _in_ the text-entry field and on the button. Can one of these be changed? Maybe the second can say "Go"?
- [ ] Add "scroll-down chevron" to http://opendata-dev.web.cern.ch/#lva to point to http://opendata-dev.web.cern.ch/#news
- [ ] "Discover the world of open data from particle physics"? I really don't like multiple compound modifiers. Makes for hideous reading to me. :P
- [ ] Display of dates for news: Can we have it say "15 November 2017" instead of "November 15th 2017"?
- [ ] Do we need the "hamburger menu" when the display is shrunk if it only has "About" under it?
- [ ] Change copyright notice to "&copy; CERN, 2015–Present" &larr; note the dash, not a hyphen.
- [ ] Use `&middot;`s to separate "© 2014 - Present CERN Terms of Use Privacy Policy Contact" like this: "© CERN 2014–Present &middot; Terms of Use &middot; Privacy Policy &middot; Contact"

**Comment by suenjedt** [comment]
Thanks for the suggestion @RaoOfPhysics
