### ISSUE TITLE
installation: uwsgi

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2053]
We currently use Flask development server to serve the COD3 application:

```console
$ grep -A 3 ^web docker-compose.yml 
web:
  restart: "always"
  build: .
  command: "cernopendata run -h 0.0.0.0"
```

which is OK for development.

Let us use `uwsgi` to serve the COD3 application for production.

Pay attention to the number of processes vs threads, e.g. try 2 processes with 2 threads each, and let's optimise the number after siege tests.

Pay attention to selecting a proper protocol, e.g. use `uwsgi_pass` in `nginx` to take advantage of the `uwsgi` custom protocol, or perhaps simply use HTTP sockets  for now (so that it will be a drop-in replacement for Flask development server), and let's see about possibly switching protocols after siege tests.

**Comment by paris737** [comment]
Sent from Yahoo Mail for iPhone


On Friday, December 8, 2017, 1:11 AM, Tibor Simko <notifications@github.com> wrote:


We currently use Flask development server to serve the COD3 application:
$ grep -A 3 ^web docker-compose.yml 
web:
  restart: "always"
  build: .
  command: "cernopendata run -h 0.0.0.0"
which is OK for development.

Let us use uwsgi to serve the COD3 application for production.

Pay attention to the number of processes vs threads, e.g. try 2 processes with 2 threads each, and let's optimise the number after siege tests.

Pay attention to selecting a proper protocol, e.g. use uwsgi_pass in nginx to take advantage of the uwsgi custom protocol, or perhaps simply use HTTP sockets for now (so that it will be a drop-in replacement for Flask development server), and let's see about possibly switching protocols after siege tests.
