### ISSUE TITLE
Feedback main page

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2084]
Feedback for the main page from Achim:

- in general there seem to be no pictures - intentional?
- for 'beginners', I find the text information on the "2nd screen" much more useful than the one on the "first screen", and the 'stories' that some people were so fond of only come on the "third screen", although they are supposed to tease the general public -> invert the order of the screens?
- the 'more' buttons on "Learn" and "Analyse" don't work
- not really my business, but shouldn't the name of the other experiments also appear explicitly in the "LEARN" section?

**Comment by suenjedt** [comment]
- Adding that fonts on 2nd and 3rd screen need to be much bigger, 
- need to reduce white space further and 
- prettify links on 2nd screen (possible that a bigger font size already does half of the job).
- the arrows to bring you from 2nd to 3rd screen does not work yet

**Comment by RaoOfPhysics** [comment]
Is the landing page responsive? It breaks quite badly when one shrinks the browser window.

**Comment by suenjedt** [comment]
Yes, of course it is. Can you specify? Note that there are some fixes pending for this.

**Comment by sefeg** [comment]
Two more observations (QA):
- Selecting a search example on the landing page that maps to a facet element (e.g. energy:7TeV) does not select the corresponding facet entry on the search result page
- News & Updates shows three of the articles twice

**Comment by RaoOfPhysics** [comment]
@suenjedt:

> Yes, of course it is. Can you specify? Note that there are some fixes pending for this.

Not at the moment, because I cannot access the website. :P

**Comment by katilp** [comment]
Achim reports that he could not find "return home" in any of the portal pages.
To me it was intuitive, but this is maybe not the case for all.

**Comment by katilp** [comment]
Clicking on Glossary in the middle part of the main page or in the "About" menu gives
![glossary](https://user-images.githubusercontent.com/5859918/34003848-adbbcb78-e0f6-11e7-8a0c-d0a7bf648dc2.PNG)

**Comment by katilp** [comment]
Further observations (by Achim from a tester):

> The "natural" initial focus is on the big "search bar". Attempts to get to
> anything useful by typing some "semi-random" search terms were unfortunately
> not successful (I personally find that the search is much improved w.r.t.
> to the old portal, if but presumably only if one knows exactly what one 
> is looking for, and knows the correct spelling, which was not the case 
> here).
> The next focus is on the individual topics ("Explore") and experiments
> ("Focus on"), which however lead to unordered collections of documenets 
> without further guidance, and were thus again not very fruitful.
> The items on the "second page" ("Learn", "Visualise", "Analyse",  then 
> finally turned out to be useful, and the further comments start from there 
> (the third page with the "stories" was not available when we tested).
> 
> Suggestion by the tester: on the firts page, put "get started" on top of the 
> arrows leading to the 2nd page, such that first time visitors are guided 
> towards it.
> (I had already suggested an "inversion" of the order of the content of the
> three pages in a previous round).

**Comment by tiborsimko** [comment]
Such as "Get Started" link could be put right at the end of the leading text, giving:

    Explore more than 1 petabyte
        of open data from particle physics!  _(Get started!)_

That would be a minimal change in this release rush that could already answer the concern.

The "get started" link would just lead to the `#lva` page.

**Comment by sefeg** [comment]
One more observation (and simple fix):

Loading the landing page, I do not fully see the arrows on the top part of the page (see images)
![image](https://user-images.githubusercontent.com/25487025/34097687-33cb6eb8-e3da-11e7-9cc4-d7b5ee1381b2.png)

![image](https://user-images.githubusercontent.com/25487025/34097705-4116f0c4-e3da-11e7-9276-8f1f4d0af504.png)

Moving them up a bit should solve the problem

**Comment by sefeg** [comment]
Here, I list all the comments / suggestions in this issue and indicate the status (as I see it). Please feel free to edit the list. 

- [x] in general there seem to be no pictures - intentional? **(yes)**
- [x] for 'beginners', I find the text information on the "2nd screen" much more useful than the one on the "first screen", and the 'stories' that some people were so fond of only come on the "third screen", although they are supposed to tease the general public -> invert the order of the screens? **(we decided to use the current design for the release)**
- [x] Adding that fonts on 2nd and 3rd screen need to be much bigger,
- [x] need to reduce white space further and
- [ ] prettify links on 2nd screen (possible that a bigger font size already does half of the job).
- [x] the arrows to bring you from 2nd to 3rd screen does not work yet
- [ ] Selecting a search example on the landing page that maps to a facet element (e.g. energy:7TeV) does not select the corresponding facet entry on the search result page
- [x] News & Updates shows three of the articles twice
the 'more' buttons on "Learn" and "Analyse" don't work
- [ ] not really my business, but shouldn't the name of the other experiments also appear explicitly in the "LEARN" section?
- [x] Achim reports that he could not find "return home" in any of the portal pages. **(We have the Open Data logo in the top bar, which is a standard approach)**
- [ ] Place a "Get Started" link right at the end of the leading text
- [ ] Move top arrow up a bit

**Comment by ioannistsanaktsidis** [comment]
Closing as already addressed in @pamfilos PR.
