### ISSUE TITLE
system: uptime robot

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2280]
Improve monitoring of COD3 functionality (home page, search page, download small text file) by introducing an alert system such as Uptime Robot.

**Comment by diegodelemos** [comment]
I have tested [Cabot](https://github.com/arachnys/cabot) as an alternative option to UptimeRobot. 
* Run on premises
* Built on top of Django (technology affinity with Invenio)
* Extensible with plugins.

After checking it locally and using current features, I've come to the conclusion that we **should go with UptimeRobot** for now since it covers the same use cases as `Cabot` does, it runs outside CERN and means zero maintenance.

Here UptimeRobot `csv` list of checks:
```csv
ID,Type,Status,"Friendly Name",URL/IP,"Keyword Type","Keyword Value",Port
779983808,HTTP,Up,"Database (querying MD based record)",http://opendata.cern.ch/docs/about,,,
779982585,HTTP,Up,"File download",http://opendata.cern.ch/record/1050/files/2010RunBlumi.txt,,,
779982582,HTTP,Up,"Home page",http://opendata.cern.ch/,,,
779982581,HTTP,Up,"HTTP Invenio Ping",http://opendata.cern.ch/ping,,,
779982575,Keyword,Up,Search,http://opendata.cern.ch/api/records/,"If Not Exists",hits,
```
