### ISSUE TITLE
Number of records in the portal does not sum up.

### ISSUE THREAD

**Issue by heitorPB** [cernopendata/opendata.cern.ch#2442]
Number of records in the portal does not sum up. For example, in the documentation:

![documentation](https://user-images.githubusercontent.com/13461702/46951210-9c862700-d087-11e8-89fa-352f124c1e02.png)

```
>>> 9 + 19 + 5 + 16 + 2 + 5 + 1
57
```

- `Datasets` is missing 1 records
- `Documentation` is missing 3 records

`Environment`, `Software` and `Supplementaries` are ok.

**Comment by IB96** [comment]
The reason of this is 1 record in Datasets is not in Collision or Derived or Simulated but it is in Datasets . And 3 records in Documentation , just like the record in Datasets , does not in About or Activities or Authors or Guide or Help or Policy or Report but they are in Documentation.
These pictures will tell better.
![dataset_extra_data](https://user-images.githubusercontent.com/22283078/47798168-7bccfb00-dd30-11e8-8169-21ad7a903d24.png)
![dataset-with all subcategories](https://user-images.githubusercontent.com/22283078/47798169-7c659180-dd30-11e8-9734-9a17a45bb480.png)
![dataset-without all subcategories](https://user-images.githubusercontent.com/22283078/47798171-7c659180-dd30-11e8-8b82-b42a6492b047.png)
![documentation-extra-data-page1](https://user-images.githubusercontent.com/22283078/47798172-7c659180-dd30-11e8-858c-26ca81270767.png)
![documentation-extra-data-page2](https://user-images.githubusercontent.com/22283078/47798173-7cfe2800-dd30-11e8-91c1-e8df73e578ea.png)
![documentation-with all subcategories](https://user-images.githubusercontent.com/22283078/47798177-7cfe2800-dd30-11e8-80dd-d2a9b84076ca.png)
![documentation-without all subcategories](https://user-images.githubusercontent.com/22283078/47798179-7d96be80-dd30-11e8-8f65-f1efcb84b687.png)

**Comment by heitorPB** [comment]
@IB96 , did you identify the dataset? And the 3 documentations? It's not easy to read in the pictures.

**Comment by IB96** [comment]
I have chosen the Dataset without Collision or Derived or Simulated first , there were 1828 results.But when I have chosen it with Collision and Derived and Simulated , there were 1827 results because "Matter Antimatter Differences (B meson decays to three hadrons) - Data Files" titled result in Dataset does not belong to Collision and Derived and Simulated but belongs to the Dataset . It is unlike the result below "Matter Antimatter Differences (B meson decays to three hadrons) - Data Files" titled result in this picture because this one belongs to Derived .

![the data in datasets](https://user-images.githubusercontent.com/22283078/47824096-e6535a80-dd73-11e8-813e-82755cfc663b.png)

Then I have chosen the Documentation without  About or Activities or Authors or Guide or Help or Policy or Report , there were 60 results . But when I have chosen it with  About and Activities and Authors and Guide and Help and Policy and Report , there were 57 results because of the same reason.Because "
CERN Open Data Privacy Policy" titled result and "CMS Pile-up Simulation" titled result and "CMS Simulated Dataset Names" titled result in Documentation do not belong to About and Activities and Authors and Guide and Help and Policy and Report but belongs to the Documentation .

I recommend to search these data on website and see these data in the website to see . 

About to make number Documentation count number to sum of the count numbers of About and Activities and Authors and Guide and Help and Policy and Report , you can move these data to About or Activities or Authors or Guide or Help or Policy or Report and then delete these data , and the same for Dataset too .

**Comment by heitorPB** [comment]
Thank you, @IB96.

Records missing complete classification:

- Dataset:
   - `Matter Antimatter Differences (B meson decays to three hadrons) - Data Files `
       http://opendata.cern.ch/record/4900
- Documentation:
   - `CERN Open Data Privacy Policy `
       http://opendata.cern.ch/docs/privacy-policy
   - `CMS Pile-up Simulation`
       http://opendata.cern.ch/record/70
   - `CMS Simulated Dataset Names`
       http://opendata.cern.ch/record/71

**Comment by IB96** [comment]
You are welcome.
