### ISSUE TITLE
CMS: ML datasets and a producer for selected 2012 MC datasets

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2444]
In connection with #2440, some ML samples will be produced from the existing AOD samples and made available on the portal.

The datasets:

http://opendata.cern.ch/record/9582 (ttbar all jets)
http://opendata.cern.ch/record/8882 (QCD flat)
http://opendata.cern.ch/record/8898 (QCD EM Enriched)

@heitorPB will check the missing configs for 8898

Emanuele has the workflow to add tracker hits in the samples.

- [x] test that the production workflow works on CMS Open Data VM
   - the VM with encapsulated slc6  #2426 can be used (it is not yet on the portal record)
- [x] prepare the CODP record for the production workflow
   - have it in a github repo (see with @caredg ): https://github.com/cms-legacydata-analyses/TrackerRecHitProducerTool
   - provide the corrsponding metadata for the CODP record (see #2588 )
- [x] produce the files and transfer to eospublic upload (see with @tiborsimko)
   - transfer ongoing to the upload area (step2: modified AODSIM, step3: ML files)
- [x] prepare the data records for the modified AODSIM, see #2526
- [x] prepare the data records and provide the metadata for  the ML files (see #2575)
- [x] if appropriate, provide an example of usage as a software record

For contributions, see also https://github.com/cernopendata/opendata.cern.ch/wiki/Contributing-content-to-CERN-Open-Data

**Comment by heitorPB** [comment]
- dataset `/QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v3/AODSIM` ( http://opendata.cern.ch/record/8898 ) was generated with the foloowing commands:

   ```
   cmsDriver.py Configuration/GenProduction/python/EightTeV QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6_cff.py --fileout file:EWK-Summer12-00045.root --mc --eventcontent RAWSIM --pileup NoPileUp --datatier GEN-SIM --conditions START50_V13::All --beamspot Realistic8TeVCollision --step GEN,SIM --datamix NODATAMIXER --python_filename EWK-Summer12-00045_1_cfg.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 96 || exit $? ; 

   cmsDriver.py step1 --filein "dbs:/QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12-START50_V13-v3/GEN-SIM" --fileout file:EWK-Summer12DR53X-00155_step1.root --pileup_input "dbs:/MinBias_TuneZ2star_8TeV-pythia6/Summer12-START50_V13-v3/GEN-SIM" --mc --eventcontent RAWSIM --runsScenarioForMC Run2012_AB_C_D_oneRunPerEra --pileup fromDB --datatier GEN-SIM-RAW --conditions START53_V7N::All --step DIGI,L1,DIGI2RAW,HLT:7E33v2 --python_filename EWK-Summer12DR53X-00155_1_cfg.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 288 || exit $? ; 

   cmsDriver.py step2 --filein file:EWK-Summer12DR53X-00155_step1.root --fileout file:EWK-Summer12DR53X-00155.root --mc --eventcontent AODSIM,DQM --datatier AODSIM,DQM --conditions START53_V7N::All --step RAW2DIGI,L1Reco,RECO,VALIDATION:validation_prod,DQM:DQMOfflinePOGMC --python_filename EWK-Summer12DR53X-00155_2_cfg.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 288 || exit $? ; 
   ```

   The configuration file used in the first cmsDriver command is available here: https://github.com/cms-sw/genproductions/blob/master/python/EightTeV/QCD_Pt/QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6_cff.py


- dataset `/QCD_Pt-15to3000_TuneZ2star_Flat_8TeV_pythia6/Summer12_DR53X-PU_RD1_START53_V7N-v1/AODSIM` ( http://opendata.cern.ch/record/8822 ):
   ```
   cmsDriver.py Configuration/GenProduction/python/EightTeV/QCD_Pt_15to3000_TuneZ2star_Flat_8TeV_pythia6_cff.py --fileout file:JME-Summer12-00024.root --mc --eventcontent RAWSIM --pileup NoPileUp --customise Configuration/StandardSequences/SimWithCastor_cff.customise,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions START50_V13::All --beamspot Realistic8TeVCollision --step GEN,SIM --datamix NODATAMIXER --python_filename JME-Summer12-00024_1_cfg.py --no_exec -n 32 || exit $? ; 
   ```
   The corresponding gen-fragment: https://github.com/cms-sw/genproductions/blob/master/python/EightTeV/QCD_Pt/QCD_Pt_15to3000_TuneZ2star_Flat_8TeV_pythia6_cff.py

**Comment by katilp** [comment]
2012 pile-up GEN-SIM needed for this will be added to open data (#2446)

**Comment by katilp** [comment]
@emanueleusai OK, I see:  @alintulu is looking at this as well, maybe check with her as well.
If needed, we can provide another GT as well. Did you check the differences between the two GT?

**Comment by emanueleusai** [comment]
Hi @katilp , thank you for the feedback. @alintulu let me know if you succeeded in running it.

Unfortunately https://cms-conddb.cern.ch/cmsDbBrowser doesn't help as it doesn't contain old 5XY tags. However, if I use:
process.load('SimGeneral.MixingModule.mix_2012_Summer_50ns_PoissonOOTPU_cfi')
instead of:
process.load('SimGeneral.MixingModule.mix_fromDB_cfi')
I can make DIGI-RAW work with V27, but it is my understanding that mix_fromDB generates samples in the more realistic run-dependent PU_RD1 configuration, opposed to PU_S10. So I assume the problem is that V27 doesn't contain the run-dependent PU information that is needed by that mixing module.

**Comment by katilp** [comment]
@emanueleusai OK, I'll check with the simulation experts and have the other GT added if it solves the problem. I thought mix_fromDB defines only how the pile-up root file location is found but I'm likely wrong then.

**Comment by katilp** [comment]
(for record: https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVRunDependentMC)

**Comment by emanueleusai** [comment]
I'm by no means an expert of simulation, but I had to specify process.mix.input.fileNames and add the special opendata xrootd redirector even with mix_2012_Summer_50ns_PoissonOOTPU_cfi, otherwise it would pull the MinBias files from the (private) central storage. Checking the two files:
https://github.com/cms-sw/cmssw/blob/master/SimGeneral/MixingModule/python/mix_fromDB_cfi.py
https://github.com/cms-sw/cmssw/blob/master/SimGeneral/MixingModule/python/mix_2012_Summer_50ns_PoissonOOTPU_cfi.py
It looks like the main difference is in the line:
https://github.com/cms-sw/cmssw/blob/master/SimGeneral/MixingModule/python/mix_fromDB_cfi.py#L17
which pulls the bunchspace,minBunch,maxBunch etc from a database (likely from the GT), opposed to:
https://github.com/cms-sw/cmssw/blob/master/SimGeneral/MixingModule/python/mix_2012_Summer_50ns_PoissonOOTPU_cfi.py#L11
and
https://github.com/cms-sw/cmssw/blob/master/SimGeneral/MixingModule/python/mix_2012_Summer_50ns_PoissonOOTPU_cfi.py#L25
where the bunch information and the probability function for the pileup are fixed.

**Comment by emanueleusai** [comment]
I am puzzled by that too. Maybe I am just missing something. But again I am no expert of GT.
My personal opinion is that as long as we stick to MC-only studies we can do with the single-profile approximation (hence, problem solved). However if and when these studies are to be tested on real data, one might benefit from having the most precise pileup simulation available.

**Comment by katilp** [comment]
Closing as all points addressed
