### ISSUE TITLE
RFC: Change "How were these data selected" to "How were these data generated" for MC?

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2470]
In data records, as a  title for "methodology", we have now "How were these data selected". This is very good for collision data, but sounds somewhat odd for simulated data, as the simulated data are not selected from anywhere (if we intend with "selected" = select a subset of data from an existing bigger set of data), they are indeed generated from the start.
Is it possible to differentiate the titles between collision data and simulated data?

For simulated data, it would be better to have:
"How were these data generated"

**Comment by tiborsimko** [comment]
(1) We can change it in the output template:

```
cernopendata/templates/cernopendata_records_ui/records/record_detail.html
```

based on dataset types.  This would require a simple if/else logic in the template code.

(2) We can introduce a new field under `methodology` called `note` or somesuch that will contain this phrase and the output templates can display it instead of the defaults.  This would require to update all records' metadata.
