### ISSUE TITLE
Sidebar slightly broken on search page

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#2516]
I was on http://opendata.cern.ch/search?subtype=Luminosity&type=Supplementaries when I noticed that the sidebar's display is slightly broken. The `3` next to `Luminosity` is offset, I think because of `Configuration RECO` occupying too much width and bumping the other two numbers down.

![screenshot_2019-02-21 cern open data portal](https://user-images.githubusercontent.com/7623019/53181676-4a867c80-35f8-11e9-8429-5585237412ce.png)

I'm on Firefox 65.0 on Kubuntu 18.04.02 LTS.

**Comment by tiborsimko** [comment]
We could simply increment the window width a bit so that most categories would be displayed nicely, however some very long category names such as "Forward and Small-x QCD Physics" may be hard to process... Either we could shorten them officially  (CC @katilp) or keep the long names and just display the first N characters (@pamfilos)

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Truncating the display (with some fade-away CSS?) might be the better option IMO.

**Comment by katilp** [comment]
@tiborsimko  we could possibly (but with some pain) shorten the names, but it is likely that sooner or later we'll run to the same problem with other attributes, so many displaying first N caracters or other is a better option.
