### ISSUE TITLE
CMS: Record for ML samples (upgrade MC for tracking GPU studies)

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2576]
From #2459
Prepare the record for the root/h5 output.

This will appear as a separate record (similar to http://opendata-dev.cern.ch/record/12100).
The underlying json will be in cms-derived-phase2-datascience.json
(to be created in https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/modules/fixtures/data/records/)

If you are comfortable with the json description, you can suggest the contents directly to @ArtemisLav in json format (see in http://opendata-dev.cern.ch/record/12100/export/json), or you can give the content to the different fields here.

Needed in particular:

- Dataset name from @adrianoDee
- Authors are Adriano di Florio, Felice Pantaleo, Maurizio Pierini? others? orcid?
- @adrianoDee will provide a description (for "abstract")
- Dataset characteristics (@adrianoDee can provide N events/entries - @tiborsimko will check n files) let us also know when the files are ready and how you will transfer
- Dataset semantics table from @adrianoDee
- Related datasets from #2520
- "How were these data generated?" (or produced) with a link to SW record to be created from a repo from @adrianoDee 
- How can you use these data? @adrianoDee can you give a brief text and and eventually a link to an example code?

I understand from @felicepantaleo and @adrianoDee that the actual  usage example for ML would be run on the output of #2520, and not on these datasets. Are these datasets then as a reference or a result of ML studies?

**Comment by AdrianoDee** [comment]
* Dataset Name: TTbar_13TeV_PU50_PixelSeeds (does it sounds?)
* Authors: Adriano di Florio, Felice Pantaleo, Maurizio Pierini
* Description - abstract: here I'm filling the json with the description (https://raw.githubusercontent.com/AdrianoDee/CNNFiltering/open/description.json). There are some records I don't know how to fix (e.g. recid, doi)
* Dataset production : https://github.com/cms-legacydata-analyses/CNNPixelSeedsProducerTool I'm just missing the eospublic path for FEVTHLT step2 files, is it somewhere?
* Dataset semantics : there's a table in the GitHub production repo but without tex-like commands. [Here](https://docs.google.com/document/d/1_2HruzC2dc80if2hxpNzL6h94Onqew9VWhKKSsV7B3g/edit?usp=sharing) a google doc with all what you need.
* Dataset characteristics: 6311 hdf files (2911 pixel only tracks events + 340 full offline tracking events) for 200 GB. I've transferred them here /eos/opendata/cms/upload/adriano/. Each file corresponds to a single step for a single event. Do you prefer a merge?

For the "how can you use these data" should we refer to the new repo with the example? Just because by now we wouldn't be able to provide an example that would make sense. By know I've included a jupyter notebook for data handling in the production repository (https://github.com/cms-legacydata-analyses/CNNPixelSeedsProducerTool/tree/master/notebooks)

**Comment by katilp** [comment]
Thanks @AdrianoDee !
You've probably used a SW record json as the base for the json you provided - we need a json similar to 
http://opendata-dev.cern.ch/record/12100/export/json 
That's not a problem, I can sort that out (and make the SW record #2589 as well), however, for the ML file record, we would need in addition dataset semantics i.e. descriptions like 

 ```
"dataset_semantics": [
      {
        "description": "Transverse momentum of the jet.",
        "type": "Float_t",
        "variable": "jetPt"
      },
      {
        "description": "Pseudorapidity (\u03b7) of the jet.",
        "type": "Float_t",
        "variable": "jetEta"
      },

```
In principle, we can convert the md table you have in readme easily. However, in view of any eventual APIs acting on the portal records, if practical, it would be good to have the exact variable names in "variable", and an entry for each variable. In the table, if I understand correctly, one would need to append in- or out- to most of the variables, and there are some variables grouped together in one line.

**Comment by AdrianoDee** [comment]
I see! No problem, I can rewrite the table in order to have the full name and an entry for each row following Kimmo example

**Comment by katilp** [comment]
@AdrianoDee Did you already have time to rewrite the table with each entry individually? Thanks!

**Comment by AdrianoDee** [comment]
I’m placing it here, inside the json

https://github.com/AdrianoDee/CNNFiltering/blob/open/description.json <https://github.com/AdrianoDee/CNNFiltering/blob/open/description.json>

**Comment by katilp** [comment]
To do:
- add a link to cernopendata-datascience in `usage` when the example is there
