### ISSUE TITLE
faq: Managing recids and DOIs

### ISSUE THREAD

**Issue by stwunsch** [cernopendata/opendata.cern.ch#2653]
Hi all,

A questions that came up in #2636:

How do you manage the recids and the DOIs?
What is the exact procedure for it and who is responsible?
There is already documentation existent?

Thanks for clarifying!

**Comment by katilp** [comment]
@tiborsimko can explain better and correct me if I'm wrong, my view just briefly: the recid's are usually taken care at the time of merge  to avoid multiple assignments so it is OK to leave just placeholders in PR.
The DOI minting is also done centrally and they are added at the time of the release, and it can be left out in PR and added to the record later.

**Comment by tiborsimko** [comment]
As @katilp mentions, the record IDs and DOIs are attributed by the CERN Open Data team.  

Concerning record IDs (`recid`), every item released on the portal should have one, as it appears in the PURL as the unique record identifier.  If you contribute PRs, it is OK to use a technique like "FIXME1", "FIXME2" and we'll take care of the rest when merging.  Note that if you need a lot of record IDs, we can agree on some special interval that you could use at will.  Note also that in those cases the "data-curation" repository serves as the central synchronisation place for them.

Concerning DOIs, not all records have them, only those where it is deemed interesting. (E.g. datasets do, but supplementary material such as trigger paths don't.) These are minted at the last moment before the public release happens when the final data are taken and everything is verified to be OK.  Once minted, it is no longer possible to change anything.

Does this answer your question?

**Comment by stwunsch** [comment]
Thanks perfect!
