### ISSUE TITLE
histogramming: load first plot by default

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3052]
(1) One issue in the new histogramming interface is the following. When users enters the `/visualise/histograms`  page for the first time, e.g. check fresh browser, they will see the following:

![h1](https://user-images.githubusercontent.com/517546/107355275-86f66000-6acf-11eb-8ff5-d460f05ed893.png)

It does not feel convenient not to see any plot at this stage. In spite of seeing the help text, people would have to think what to do.

For this reason, the PROD was pre-selecting E1, so that "at least one example plot" would be shown to newcomers.

(1a) Can we pre-select E1 (or some other reasonable entity), so that people would see a plot when entering the page?
 
(1b) Note that the behaviour from PROD was not ideal either, e.g. if you change the event types from the menu, the plot may not be shown... But at least it was upon first page view.

(2) BTW a minor stylistic issue observed on the side: (Qutebrowser, Firefox)

![h2](https://user-images.githubusercontent.com/517546/107355668-169c0e80-6ad0-11eb-9f6e-59c5c8fe864b.png)

![h3](https://user-images.githubusercontent.com/517546/107355812-48ad7080-6ad0-11eb-9163-83864e272dc8.png)

see how "Log Y" is hidden because "Set bin width" takes more horizontal and vertical space.

**Comment by diegodelemos** [comment]
Regarding (1) this is most probably because the [file was not yet downloaded](https://github.com/cernopendata/opendata.cern.ch/blob/203fc8b8b8b06d29786d426ba12adbadd5d5f77c/cernopendata/modules/theme/assets/semantic-ui/js/visualise/visualise_histograms.js#L107-L130) by the time the [programmatic click is performed](https://github.com/cernopendata/opendata.cern.ch/blob/203fc8b8b8b06d29786d426ba12adbadd5d5f77c/cernopendata/modules/theme/assets/semantic-ui/js/visualise/visualise_histograms.js#L137-L139). Using setTimeout there doesn't seem very robust.
