### ISSUE TITLE
devops: EOS links to configuration files

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3063]
Example: https://opendata.cern.ch/record/13072 and the link for LHE:

![lhe](https://user-images.githubusercontent.com/517546/107950934-c1607100-6f97-11eb-94ef-4e503aca184d.png)

In PROD, the link works, and the file is served from EOS via nginx reverse proxy.

In DEV, the link does not and leads to "Page not found".

We should DEV's nginx configuration to see whether `/eos/opendata/...` URLs are well redirected to EOSPUBLICHTTP  via reverse proxy.

**Comment by diegodelemos** [comment]
Fixed in [deployment repo](https://gitlab.cern.ch/cernopendata/deployment/-/merge_requests/1/diffs?commit_id=19cf26d517f6a1dd64ad853100bf6c6eee8f7bcb), see https://opendata-dev.cern.ch/record/13072, [the reverse proxy `/eos/opendata` location](https://github.com/cernopendata/opendata.cern.ch/blob/c800b6e4fcb5463a94551d1ed1627a238f064359/nginx/localhost.conf#L66-L72) was missing from nginx config in `opendata-dev.cern.ch`.
