### ISSUE TITLE
/glossary link is broken

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3087]
PROD is OK: http://opendata.cern.ch/glossary

DEV is not: http://opendata-dev.cern.ch/glossary

The glossary link exists e.g. on the CERN Open Data portal home page.

This issue is related to supporting old URLs and converting them to new faceted search pages; see also #3030 and #3060.

**Comment by tiborsimko** [comment]
Note: this could be due to Glossary type not having any subtype.  Similar thing is the News type.

We can improve the old URL recogniser for these cases... But I wonder whether we shouldn't move both Glossary and News under Documentation at the same time. They are definitely related, and it would also help with the UI as a by product :wink:  (see #3080)

Let us therefore amend both the fixtures, and update the URL recogniser configuration, to fix both of these issues advantageously.

**Comment by mvidalgarcia** [comment]
It seems like the URL is properly translated and other single types without subtype as "News" work as expected (http://opendata-dev.cern.ch/search?type=News)

I've noticed that some of the facets disappear when sorting all search results by "Title A-Z", namely Glossary and News, therefore http://opendata-dev.cern.ch/api/records/?q=&page=1&size=10&type=Glossary&sort=title or http://opendata-dev.cern.ch/api/records/?q=&page=1&size=10&type=News&sort=title return 0 hits, while removing `sort=title` returns the expected results.

Since http://opendata-dev.cern.ch/glossary [is translated ](https://github.com/cernopendata/opendata.cern.ch/blob/a0ce88441a259ded0fd2808f4283b2b557c9c989/cernopendata/modules/pages/views.py#L160-L163)to http://opendata-dev.cern.ch/search?f=type%3AGlossary&sort=title which calls http://opendata-dev.cern.ch/api/records/?q=&sort=title&page=1&size=10&type=Glossary, (note the `sort`) 0 results are returned.

OTOH, if I select the "Glossary" facet directly from the Search UI, I get [the React minified error](https://github.com/cernopendata/opendata.cern.ch/issues/3082), which apparently means that [a React child is an object ](https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Bname%7D) when it shouldn't.

**Comment by tiborsimko** [comment]
> I've noticed that some of the facets disappear when sorting all search results by "Title A-Z", namely Glossary and News, therefore http://opendata-dev.cern.ch/api/records/?q=&page=1&size=10&type=Glossary&sort=title or http://opendata-dev.cern.ch/api/records/?q=&page=1&size=10&type=News&sort=title return 0 hits, while removing sort=title returns the expected results.

Indeed, interesting observation! @ParthS007 Have you experimented with `title` analysers and mappings for the other document types as well? (`cernopendata/mappings/v7/records/docs-v1.0.0.json` and `cernopendata/mappings/v7/records/glossary-term-v1.0.0.json`)
