### ISSUE TITLE
Should on-demand datasets by included default?

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3089]
The on-demand choice is now down in the left bar and not very visible, and on-demand datasets are included as default.

The default search on CMS simulated datasets:

https://opendata-dev.cern.ch/search?q=&f=experiment%3ACMS&f=type%3ADataset%2Bsubtype%3ASimulated&l=list&order=asc&p=1&s=10&sort=mostrecent

has the on-demand datasets right on the top. This gives a bad first impression as it looks like no datasets are actually available. 

Can the default be brought back to not including the on-demand datasets? Or not bringing them on top?

**Comment by tiborsimko** [comment]
We removed the checkbox feature to be a sort of forward-looking, because it seems there will be quite many datasets available on tapes only. (These will also be in a sort of "on-demand" status, though "faster" than the ones living in CMS grid sites.) 

So I'd probably favour your second suggestion, to rank them very low in all queries. 

Basically, if a record contains:

```json
  "distribution": {
      "availability": "ondemand",
```

then we should rank it down really low, after all the other results.

Will this do?

**Comment by katilp** [comment]
That sounds good to me. 

Ideally, if feasible, each of the on-demand datasets (at least those hosted on "your" side) could then have some files accessible on disk for a quick inspection.
