### ISSUE TITLE
CMS: wrong or missing MC categories

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3235]
Categories to be fixed for the 2015 MC datasets:

- [x] ST_  Standard Model Physics/Top physics
- [x] ExtendedWeakIsoSpin Exo / Misc
- [x] EEG SM /EWK
- [x] PhotonIndBkg SM /EWK
- [x] Monotop Exostica/Dark Matter
- [x] ZZJ SM / EWK
- [x] Dstar Ds B physics and Quarkonia
- [x] Single Double Physics Modelling
- [x]	TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8	Standard Model Physics/Top physics
- [x] 1	WGJJToLNu_EWK_QCD_TuneCUETP8M1_13TeV-madgraph-pythia8	Standard Model Physics/ElectroWeak
- [x] 2	WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8	Standard Model Physics/ElectroWeak.
- [x] 3	tZq_nunu_4f_13TeV-amcatnlo-pythia8_TuneCUETP8M1	Standard Model Physics/Top physics
- [x] 4	GluGluHToEEG_M125_MLL-0To50_Dalitz_13TeV_madgraph_pythia8	Higgs Physics/Standard Model
- [x] 5	GluGluSpin0ToGG_W-0p014_M-3750_TuneCUEP8M1_13TeV-pythia8	Higgs Physics/BSM
- [x] 6	GluGluSpin0ToZGamma_ZToQQ_W_0-p-014_M_1000_TuneCUEP8M1_13TeV_pythia8	Higgs Physics/BSM
- [x] 7	GluGluWWTo2L2Nu_HInt_MCFM_13TeV	Higgs Physics/Standard Model
- [x] 8	GluGluWWTo2L2Nu_MCFM_13TeV	Standard Model Physics/ElectroWeak
- [x] 9	HSCPgmstau_M-432_TuneZ2star_13TeV-pythia6	Exotica/Miscellaneous
- [x] 10	InclusivebtoMu_bMuonFilter_TuneCUEP8M1_13TeV-pythia8-evtgen	B physics and Quarkonia
- [x] 11	ST_t-channel_4f_scaleup_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1	Standard Model Physics/Top physics
- [x] 12	SingleNeutron_E0to200	Physics Modelling
- [x] 13	TTToSemiLeptonic_13TeV-powheg	Standard Model Physics/Top physics
- [x]	TTZToQQ_TuneCUETP8M1_13TeV-amcatnlo-pythia8	Standard Model Physics/Top physics
- [x] 15	Unpart_ZToLL_SU-0_dU-1p70_LU-15_TuneCUETP8M1_13TeV-pythia8	Exotica/ Extra dimensions
- [x] 16	WLLJJToLNu_M-4to60_EWK_QCD_TuneCUETP8M1_13TeV-madgraph-pythia8	Standard Model Physics/ElectroWeak
- [x] 17	WLLJJToLNu_M-60_EWK_13TeV-madgraph-pythia8	(Exotica/Heavy Gauge Bosons) SM /EWK
- [x] 18	WZJJ_EWK_13TeV-madgraph-pythia8	Standard Model Physics/ElectroWeak
- [x] 19	tZq_ll_4f_13TeV-amcatnlo-pythia8_TuneCUETP8M1	Standard Model Physics/Top physics
- [x] 	ttHJetToNonbb_M125_13TeV_amcatnloFXFX_madspin_pythia8_mWCutfix	Higgs Physics/Standard Model
- [x] 21	ttbb_4FS_ckm_amcatnlo_madspin_pythia8	Standard Model Physics/Top physics

**Comment by ssekmen** [comment]
Hi @katilp ,
This categorization may have been intentional, but I still wanted to check:
I see that the singletop samples are listed under miscellaneous rather than top physics:

/ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v2/
/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/
/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/
/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/

https://opendata.cern.ch/record/19395
https://opendata.cern.ch/record/19397
https://opendata.cern.ch/record/19419
https://opendata.cern.ch/record/19412

**Comment by katilp** [comment]
Closed in PR #3249
