### ISSUE TITLE
Lack of HTTPS Forcing

### ISSUE THREAD

**Issue by mbiesiad** [cernopendata/opendata.cern.ch#3393]
Hi,

# Repro steps:
1. Go to http://opendata.cern.ch/ or for example http://opendata.cern.ch/search?page=1&size=20&q=opendata
2. See no HTTPS forcing - the same with assets there, search feature etc.

Best wishes,

**Comment by tiborsimko** [comment]
The HTTPS is not being forced upon by design actually, because some very old open data analysis examples (that are running on ten-year old software stack!) cannot easily use the new TLS standards that HTTPS would require. Hence we keep both HTTP and HTTPS connections on for any "legacy" needs of this kind.
