### ISSUE TITLE
Ensure that the pipelines check the code style with black

### ISSUE THREAD

**Issue by psaiz** [cernopendata/opendata.cern.ch#3459]
Similar to the inveniosoftware modules, the pipelines of opendata.cern.ch should check the code style of all the python files

**Comment by tiborsimko** [comment]
Please check `cernopendata-client` that already has these checks, for example:

- https://github.com/cernopendata/cernopendata-client/blob/master/run-tests.sh#L20
- https://github.com/cernopendata/cernopendata-client/blob/master/.github/workflows/ci.yml#L20

For the commit converting existing code to use black formatting, please use a neutral author such as:

```console
$ git commit --author='CERN Open Data team <opendata-team@cern.ch>' -m 'global: format with black' 
```

For example:

- https://github.com/reanahub/reana-server/commit/b80cf8337558f0bd4cd25ea0ae75f193be4fe12c.patch

We were doing this in order to respect the past authorship of the existing code, so to speak.
