### ISSUE TITLE
Wrong link to glossary css

### ISSUE THREAD

**Issue by psaiz** [cernopendata/opendata.cern.ch#3466]
* Go to a record, like https://opendata.cern.ch/record/14
* Open the development tools in the browser
* Move the mouse over the word "events"
The console shows an error of a missing png. The path to the png looks suspicious.

![Screenshot 2023-11-20 at 10 49 00](https://github.com/cernopendata/opendata.cern.ch/assets/12909623/c644fc07-7d0d-4b9b-a7d0-d2601c30a998)

**Comment by tiborsimko** [comment]
The given image "ui_close_sm" comes from the jquery zglossary package. We don't really need an image to close the popup, I think, since the hovered text box auto-closes when a person moves the mouse. I think we can do without it.

BTW does this occur also in the `master` branch where the underlying glossary business was updated as part of Angular -> React move? Perhaps it might have been cleaned there.

**Comment by psaiz** [comment]
This does not happen in opendata-qa. So, once we deploy those changes in production, this will be solved
