### ISSUE TITLE
records: formatting of "Related items" box

### ISSUE THREAD

**Issue by ayrodrig** [cernopendata/opendata.cern.ch#557]
In Record 101 http://opendata.cern.ch/record/101:

> Related items
The expected output is a histogram file Record 5 , Record 0 , Record 0

Record 5 is not a related item in this case.
Record 0 is a broken link.

Would you expect a histogram file in those records? I could provide you two pdf files: one for the histogram file output of each analysis.

**Comment by suenjedt** [comment]
@katilp : what would you suggest. Attach to a record or a separate record for the output example(png)?

**Comment by RaoOfPhysics** [comment]
@suenjedt: I can't comment on this! I leave it to @katilp and @ayrodrig to weigh in.

**Comment by pherterich** [comment]
As this issue is not solved yet, @tiborsimko do you have a preferred technical solution to do this? Is there a possibility to include them in the text without it getting messy? I have the feeling a separate record for each png is a bit too much but I don't want them to get lost in the file attachments either.

**Comment by tiborsimko** [comment]
@pherterich @AnxhelaDani I'd simply attach the plots to the analysis record and display them in the Description section (or some other appropriate section) with a bit of commentary.

**Comment by tiborsimko** [comment]
I'll take care of this..

**Comment by tiborsimko** [comment]
OK, I added the two plots.  We can improve the display later, that may be for another issue...
