### ISSUE TITLE
Text and links in the CMS VM record

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#633]
For the VM record http://opendata.cern.ch/record/250/citations:
- the description text needs to be changed as it refers to slc6, I would correct it to
"The virtual machine image is based on CernVM (cernvm.cern.ch), with Scientific Linux CERN 5 (slc5), which is the environment needed for the CMSSW release to be used with the 2010 CMS open data. Access to the data is through XRootD"
- the links are not visible for the validation report and the issues
- the contextualisation file should be added (I'll ask Adam)

Why does the tools collection http://opendata.cern.ch/collection/CMS-Tools give the link to the record with "citations":  http://opendata.cern.ch/record/250/citations

**Comment by pherterich** [comment]
@tiborsimko how to we hide the old versions? Template or actually deleting them?

**Comment by tiborsimko** [comment]
Only rc7 is showed on DEV, so I guess this ticket can be closed.

(In theory, yes, both techniques are possible, either to delete the file or to amend the templates to display only latest version. In practice, once a file is published, we should refrain from deleting it as much as reasonably possible, otherwise the system may be percieved as not keeping up to its archiving functionality...)
