### ISSUE TITLE
ALICE data upload

### ISSUE THREAD

**Issue by mgheata** [cernopendata/opendata.cern.ch#772]
Dear Tibor,

We are ready to upload ~10 TBytes of 2010 ALICE data, including metadata in json format. 
We need access rights for Costin Grigoras who will take care of this task, to transfer the data on:
root://eospublic.cern.ch//eos/opendata/alice/
(please confirm the xrood location, was it with "upload" at the end?)

Best regards,
Mihaela

**Comment by pherterich** [comment]
Wow, that's great news. Can I see an example of the json metadata somewhere so I can start thinking of a smart way to convert them? Thanks!

**Comment by mgheata** [comment]
Hi,
Please see ticket #354 which is the proposal of Tibor: we will provide extra info in the "file_details" tag.

Best, Mihaela

**Comment by tiborsimko** [comment]
@mgheata The setup is ready, Costin can start uploading data to `eospublic.cern.ch//eos/opendata/alice/upload/`.  Please keep the same directory organisation, and please let me know when it's done.

**Comment by mgheata** [comment]
Hi Tibor, 
it looks that we got out of quota after uploading 20% of data:
Run: [ERROR] Server responded with an error: [3005] Unable to get quota space - quota not defined or exhausted /eos/opendata/alice/upload/2010/LHC10h/000139465/ESD/5081/AliESDs.root; Disk quota exceeded

We need something like 10 TBytes.
Best, 
Mihaela

**Comment by tiborsimko** [comment]
The quota should be OK now, please retry uploading the rest of the files.

**Comment by mgheata** [comment]
Dear Tibor,

We finished to copy the data and the json files.

Best regards,
Mihaela

**Comment by tiborsimko** [comment]
The data files were moved to EOS in May, I'm now going to create record skeletons and upload them to DEV.

**Comment by tiborsimko** [comment]
The new ALICE data have been deployed on DEV:

- http://opendatadev.cern.ch/collection/ALICE-Reconstructed-Data

Here are some notes tasks before we can move them to production:

- @mgheata I've taken the data "as is", so e.g. the new JSON files are named like `LHC10h_PbPb_ESD_139038.json` while the old files were called `LHC2010b_pp_ESD_117222.json`.  Will your scripts work with the two versions? Do we standardise onto `LHC10h` or `LHC2010h`? (Note that EOS file paths are the same, only JSON filenames differ.)

- @mgheata Can you please calculate the total number of events in each dataset?  I left FIXME there for the time being.

- @pherterich Can you please mint new DOIs and update the XML file?  I left FIXME values like `10.7483/OPENDATA.ALICE.FIXME.1105` there.

- @mgheata @pherterich Can you please check general metadata and correct/enrich them if needed?  I basically copied the common part from the past.

- @mgheata Any news item to prepare for the public announcement of the release? http://opendatadev.cern.ch/news

- @mgheata Any wishes to change the ALICE collection pages text or look and feel?  Introduce not only "Education" but "Research" corner due to amount of data?  Etc.

P.S. If some of the above items do require work, then please open new issues and/or new PRs for them.

**Comment by mgheata** [comment]
Hi Tibor,
- We decided to standardize on LHC10h rather than LHC2010h (I remember we discussed the issue some time ago), so it is best to change them all to this style - I will adapt the GUI accordingly.
- I will send you the numbers of events per dataset
- For the news, there is nothing for now, we want to fix the data and update the analysis modules first
- I will think about restructuring to include Research, this is correlated with the new analysis we are introducing

**Comment by mgheata** [comment]
Hi Tibor,

LHC10c_pp_ESD_120824 ____ 4 161 939 events
LHC10c_pp_ESD_120822 ____ 7 051 925 events
LHC10c_pp_ESD_120616 ____ 6 013 407 events
LHC10c_pp_ESD_120505 ____ 4 562 205 events
LHC10c_pp_ESD_120244 ____ 2 444 747 events
LHC10c_pp_ESD_120076 ____ 3 732 298 events

LHC10h_PbPb_ESD_139465 ____ 1 076 914 events
LHC10h_PbPb_ESD_139438 ____  281 139 events
LHC10h_PbPb_ESD_139437 ____  882159 events
LHC10h_PbPb_ESD_139173 ____  559 371 events 

Regards,
Mihaela

**Comment by pherterich** [comment]
@mgheata still missing the number of events for LHC10h_PbPb_ESD_139038 and LHC10c_pp_ESD_129829
Let me know if you want any other metadata added/changed. Thanks!

**Comment by mgheata** [comment]
LHC10h_PbPb_ESD_139038 --744 551
LHC10c_pp_ESD_120829--4 113 427 
I don't see  LHC10c_pp_ESD_120829 in the list of runs
Thanks!
No other changes. 

Mihaela

**Comment by pherterich** [comment]
That might be a typo I guess. Because all the files LHC10c/000120829/something.root are attached to the dataset LHC10c_pp_ESD_129829 which I can't find in your list. I will fix it.
