### ISSUE TITLE
Collision types

### ISSUE THREAD

**Issue by AnxhelaDani** [cernopendata/opendata.cern.ch#877]
@katilp about the collision types, can we use them as keyword in `653 $a` field  or facet instead of a separate MARC field?

**Comment by katilp** [comment]
I do not know much about the fields and keywords, maybe @tiborsimko can advice?

**Comment by tiborsimko** [comment]
If we want to have collision types presented on the search results pages in the separate facet, then we must use separate MARC tag to store them.  If we put them into the keyword field, then there would be one facet called "Keywords" that would offer any value present in this field.  

So this is basically a question whether it makes sense to create an independent search panel for collision types, or whether they may be presented as other keywords. For example, on this page:

- http://doc.rero.ch/search?p=of

There are seven different factets: Document type, Institution, Specific collection, Language, Author, Domain, Keyword.  Would you see "collision types" as one of those?

See also #865.  Personally I'd propose to limit the number of independent facets down to a usable minimum in order to keep the UI clean...

**Comment by AnxhelaDani** [comment]
After discussion with @pherterich and as collision types are related with collision energy, the MARC field ``` 942__ $t ``` will be used for Collision Types of Primary, Derived and MC Datasets.

**Comment by pherterich** [comment]
If we agree on how we write it, @tiborsimko can you add the field to all of them? Options are 
proton -> proton
Proton -> Proton
P -> P
anything else we haven't thought of. Smart suggestions to replace -> with something else are also welcome!

**Comment by pherterich** [comment]
proton-proton it is obviously

**Comment by tiborsimko** [comment]
Can we postpone this once we have some LEP data in sight?

**Comment by pherterich** [comment]
Wouldn't it be easier to add it now and not show it than having to touch all the records again later? Especially as this is a job that can be scripted as it's the same for all the datasets. Sounds easier to me than having to do it later.

**Comment by tiborsimko** [comment]
My thinking was the following: adding "proton-proton" information should be done globally to the past files as well, not only to the current CMS Run2011A files we are sprinting on now, hence I considered it as part of another milestone.  If we add it only to the new files, we'd have inconsistencies... 

(Besides, this need will appear very naturally later when we shall have some "electron-positron" data.)

**Comment by katilp** [comment]
NB that we may have heavy ion data from the LHC (lead-lead). What do we have in the ALICE data records (or are they proton-proton as well)?

**Comment by pherterich** [comment]
Well, I thought going backwards and adding it for 2010 data that is currently only like 50 records is something we can do manually and it's better to do it now than in 1-2 years. ALICE already has some pb-pb datasets on the portal (which is mentioned in their title and the description, but not tagged in any way).

**Comment by katilp** [comment]
:+1: 
If this delays the release, it is not a problem, we do not have a fixed date for the release.
(it will in any case delay a release, sooner or later, and the later it is done, the more it will delay :-) )

**Comment by tiborsimko** [comment]
@pherterich Sure, if you edit the records, then please send a PR for this.  (Note that we have 208 records in the master branch, not only 50.)

**Comment by tiborsimko** [comment]
As discussed with @katilp @ArtemisLav, let's do this during COD2 -> COD3 record conversion.
The values to use are "pp" for proton-proton collisions, and, when appropriate "PbPb" for ALICE.
