### ISSUE TITLE
ALICE record appears in CMS open data instructions

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#946]
http://opendatadev.cern.ch/collection/CMS-Open-Data-Instructions

<img width="891" alt="screen shot 2016-03-15 at 5 24 25 pm" src="https://cloud.githubusercontent.com/assets/496503/13787189/d3cec016-ead2-11e5-8e60-51c855462539.png">

**Comment by tpmccauley** [comment]
When one clicks on it ones goes to a CMS resource: 
http://opendatadev.cern.ch/record/55

**Comment by tpmccauley** [comment]
It seems that there are two record with the same numbers. 55 is used for the ALICE Masterclasses record as well:

https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/testsuite/data/alice/alice-learning-resources.xml#L3

compare with:

https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/testsuite/data/cms/cms-open-data-instructions.xml#L3

**Comment by artfisica** [comment]
Dear OpenData Team,

In order to start the integration of the new ATLAS data&tools release,
I have been following the instructions in: https://github.com/cernopendata/opendata.cern.ch/blob/master/DEVELOPING.rst#detailed-installation-instructions

And everything looks fine, but at the end when the web container is running, here some of the last lines:


web_1     |  * Running on http://0.0.0.0:28080/ (Press CTRL+C to quit)
web_1     |  * Restarting with inotify reloader
web_1     | --------------------------------------------------------------------------------
web_1     | DEBUG in factory [/code/invenio/base/factory.py:237]:
web_1     | DEBUG = True
web_1     | --------------------------------------------------------------------------------
web_1     | --------------------------------------------------------------------------------
web_1     | DEBUG in factory [/code/invenio/base/factory.py:237]:
web_1     | DEBUG_TB_INTERCEPT_REDIRECTS = False
web_1     | --------------------------------------------------------------------------------
web_1     | /usr/local/lib/python2.7/site-packages/pyparsing.py:3546: DeprecationWarning: Operator '<<' is deprecated, use '<<=' instead
web_1     |   ret << Group( Suppress(opener) + ZeroOrMore( ignoreExpr | ret | content ) + Suppress(closer) )
web_1     |
web_1     | /code/invenio/legacy/external_authentication/__init__.py:29: RemovedInInvenio21Warning: External authentication pluugins have been deprecated. Please use 'invenio.modules.oauthclient' or Flask-SSO instead.
web_1     |   RemovedInInvenio21Warning)
web_1     |
web_1     | /usr/local/lib/python2.7/site-packages/wtforms/ext/sqlalchemy/__init__.py:9: DeprecationWarning: wtforms.ext.sqlalchemy is deprecated, and will be removed in WTForms 3.0. The package has been extracted to a separate package wtforms_sqlalchemy: https://github.com/wtforms/wtforms-sqlalchemy .
web_1     | Or alternately, check out the WTForms-Alchemy package which provides declarative mapping and more: https://github.com/kvesteri/wtforms-alchemy
web_1     |   DeprecationWarning
web_1     |
web_1     |  * Debugger is active!
web_1     |  * Debugger pin code: 119-083-381
mysql_1   | 2016-05-02T14:37:13.526281Z 30 [Note] Aborted connection 30 to db: 'invenio' user: 'invenio' host: '172.17.0.4' (Got an error reading communication packets)
mysql_1   | 2016-05-02T14:37:13.526688Z 31 [Note] Aborted connection 31 to db: 'invenio' user: 'invenio' host: '172.17.0.4' (Got an error reading communication packets)
mysql_1   | 2016-05-02T14:38:14.978135Z 34 [Note] Aborted connection 34 to db: 'invenio' user: 'invenio' host: '172.17.0.4' (Got an error reading communication packets)



But I cannot find the website in the host http://127.0.0.1:28080/ (neither in localhost) and I a wondering if this is symptom that in fact not all is fine.

Do you have an idea of what can I try? Thank you for any help.

Cheers,
Arturo

**Comment by artfisica** [comment]
Dear All,

excuse me for the self-reply but I went deeper in the docker documentation to check the status of the containers and I do find the “ opendatacernch_web” in “127.0.0.1:28080” but for some reason I cannot see it in my browser.

And also using the 192.168.99.100 of the VM as explained in: https://docs.docker.com/engine/installation/mac/#access-container-ports


                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

arturos@arturos-mac-air:~/ATLAS/Outreach/opendata/opendata.cern.ch<http://opendata.cern.ch>$ docker-machine ip default
192.168.99.100
arturos@arturos-mac-air:~/ATLAS/Outreach/opendata/opendata.cern.ch<http://opendata.cern.ch>$ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                        NAMES
5e594697e082        opendatacernch_worker   "/code/scripts/docker"   8 hours ago         Up About a minute                                opendatacernch_worker_1
f15418e459f5        opendatacernch_web      "/code/scripts/docker"   8 hours ago         Up About a minute   127.0.0.1:28080->28080/tcp   opendatacernch_web_1
b54cd7cae998        mysql                   "docker-entrypoint.sh"   8 hours ago         Up About a minute   127.0.0.1:23306->3306/tcp    opendatacernch_mysql_1
e9406060a794        redis                   "docker-entrypoint.sh"   8 hours ago         Up About a minute   127.0.0.1:26379->6379/tcp    opendatacernch_redis_1
arturos@arturos-mac-air:~/ATLAS/Outreach/opendata/opendata.cern.ch<http://opendata.cern.ch>$



Thank you for any advice,
Cheers,
Arturo



On 02 May 2016, at 16:49, Arturos Sanchez Pineda <Arturo.Rodolfo.Sanchez.Pineda@cern.ch<mailto:Arturo.Rodolfo.Sanchez.Pineda@cern.ch>> wrote:

Dear OpenData Team,

In order to start the integration of the new ATLAS data&tools release,
I have been following the instructions in: https://github.com/cernopendata/opendata.cern.ch/blob/master/DEVELOPING.rst#detailed-installation-instructions

And everything looks fine, but at the end when the web container is running, here some of the last lines:


web_1     |  * Running on http://0.0.0.0:28080/ (Press CTRL+C to quit)
web_1     |  * Restarting with inotify reloader
web_1     | --------------------------------------------------------------------------------
web_1     | DEBUG in factory [/code/invenio/base/factory.py:237]:
web_1     | DEBUG = True
web_1     | --------------------------------------------------------------------------------
web_1     | --------------------------------------------------------------------------------
web_1     | DEBUG in factory [/code/invenio/base/factory.py:237]:
web_1     | DEBUG_TB_INTERCEPT_REDIRECTS = False
web_1     | --------------------------------------------------------------------------------
web_1     | /usr/local/lib/python2.7/site-packages/pyparsing.py:3546: DeprecationWarning: Operator '<<' is deprecated, use '<<=' instead
web_1     |   ret << Group( Suppress(opener) + ZeroOrMore( ignoreExpr | ret | content ) + Suppress(closer) )
web_1     |
web_1     | /code/invenio/legacy/external_authentication/__init__.py:29: RemovedInInvenio21Warning: External authentication pluugins have been deprecated. Please use 'invenio.modules.oauthclient' or Flask-SSO instead.
web_1     |   RemovedInInvenio21Warning)
web_1     |
web_1     | /usr/local/lib/python2.7/site-packages/wtforms/ext/sqlalchemy/__init__.py:9: DeprecationWarning: wtforms.ext.sqlalchemy is deprecated, and will be removed in WTForms 3.0. The package has been extracted to a separate package wtforms_sqlalchemy: https://github.com/wtforms/wtforms-sqlalchemy .
web_1     | Or alternately, check out the WTForms-Alchemy package which provides declarative mapping and more: https://github.com/kvesteri/wtforms-alchemy
web_1     |   DeprecationWarning
web_1     |
web_1     |  * Debugger is active!
web_1     |  * Debugger pin code: 119-083-381
mysql_1   | 2016-05-02T14:37:13.526281Z 30 [Note] Aborted connection 30 to db: 'invenio' user: 'invenio' host: '172.17.0.4' (Got an error reading communication packets)
mysql_1   | 2016-05-02T14:37:13.526688Z 31 [Note] Aborted connection 31 to db: 'invenio' user: 'invenio' host: '172.17.0.4' (Got an error reading communication packets)
mysql_1   | 2016-05-02T14:38:14.978135Z 34 [Note] Aborted connection 34 to db: 'invenio' user: 'invenio' host: '172.17.0.4' (Got an error reading communication packets)



But I cannot find the website in the host http://127.0.0.1:28080/ (neither in localhost) and I a wondering if this is symptom that in fact not all is fine.

Do you have an idea of what can I try? Thank you for any help.

Cheers,
Arturo
